<h1 align="center" style="color:blue;">
📘 Formation à la bibliothèque Pandas : Manipulation et analyse de données
</h1>

<p align="center">
<b>Réalisé par :</b> SAKPANI Paguiyedou<br>
Étudiant en Licence Fondamentale – Sciences de l'Ingénieur<br>
Filière : Intelligence Artificielle & Big Data<br>
École Polytechnique de Lomé (EPL)
</p>

<h3 style="color:#1f77b4;">📖 Introduction</h3>

<p style="text-align:justify;">
Dans le domaine de la <strong>Data Science</strong>, les données proviennent de nombreuses sources (fichiers CSV, fichiers Excel, bases de données, API, etc.) et se présentent sous différentes formes. Afin de les exploiter efficacement, il est indispensable de disposer d'un outil capable de les importer, de les organiser, de les nettoyer, de les transformer et de les analyser.
</p>

<p style="text-align:justify;">
C'est précisément le rôle de la <strong>bibliothèque Pandas</strong>, l'une des bibliothèques les plus utilisées en Python pour la manipulation et l'analyse de données. Elle fournit des structures de données puissantes et intuitives qui permettent de travailler efficacement sur des jeux de données de toute taille.
</p>

<p style="text-align:justify; color:#c0392b;">
Le <strong>DataFrame</strong> est la structure de données principale de Pandas. Il permet de représenter les données sous la forme d'un tableau à deux dimensions, composé de lignes et de colonnes dont chacune possède un nom explicite. À l'image d'un tableau Excel ou d'une table d'une base de données, chaque colonne représente une variable et chaque ligne correspond à une observation (ou individu).
</p>

<p style="text-align:justify;">
Chaque colonne d'un <strong>DataFrame</strong> possède un type de données unique (<em>entier</em>, <em>réel</em>, <em>chaîne de caractères</em>, <em>date</em>, etc.), tandis que différentes colonnes peuvent contenir des types différents. Cette organisation rend les données faciles à manipuler et permet d'effectuer de nombreuses opérations telles que le filtrage, le tri, les calculs statistiques, la fusion de tableaux, le traitement des valeurs manquantes et la visualisation des données.
</p>

<p style="text-align:justify;">
Au cours de cette formation, nous découvrirons progressivement les principales fonctionnalités de Pandas afin d'acquérir les compétences nécessaires pour manipuler des données réelles et réaliser des analyses efficaces dans le cadre de projets de Data Science.
</p>

<h2 style ='color : blue'>A. Introduction et structures de données (Series, DataFrame)</h2>

<h3><p></p>1 . La Series</p>
<p><p style = "color : red">Definition :</p>une Series, c'est une colonne de données à une seule dimension. Chaque valeur est associée à une étiquette qu'on appelle un "index" — un peu comme une colonne Excel avec des numéros de ligne à gauche.<br style ="color : red" </p></h3>

In [1]:
import pandas as pd ##Importation de la librairie pandas

In [2]:
ages = pd.Series([19,24,45])

In [3]:
ages  ##Resultat

0    19
1    24
2    45
dtype: int64

In [4]:
##A gauche on a (0,1,2) , c'est lindex automatique.A droite , ce sont des valeurs .

In [8]:
ages =pd.Series([19,24,45], index = ["Sakapni", "Pagui", "Toto"]) ##Il faut note aussi que je peut choisir moi-memes les etiques de l'index

In [9]:
ages

Sakapni    19
Pagui      24
Toto       45
dtype: int64

<h3><p style = "color : red"> 2. Le Data Frame</p><p><p  style = "color :red" >Définition :</p> un DataFrame, c'est un tableau à deux dimensions — plusieurs colonnes (donc plusieurs Series regroupées ensemble), avec des noms de colonnes et un index de lignes. C'est la structure centrale de Pandas.</p>

<p style = "color : red">Utilité :</p> c'est ce que tu utiliseras tout le temps en pratique, car un vrai dataset a toujours plusieurs colonnes (nom, âge, prime, type de contrat, etc.), pas une seule.</h3>

In [27]:
data = {
    'nom': ['Alice', 'Bob', 'Chloé'],
    'age': [25, 30, 35],
    'Filiere': ['IA', 'GC', 'GM']
}
df = pd.DataFrame(data)   ## ma premire fois de crrer un DataFrame en avec la librairie pandas .Quelle joie.
df

     nom  age Filiere
0  Alice   25      IA
1    Bob   30      GC
2  Chloé   35      GM

<h3><p style = "color : blue"> 2.1 -Comprendre la structure d'un DataFrame</p>Une fois que tu as un DataFrame, tu veux souvent savoir ce qu'il contient sans tout afficher. Voici les commandes de base, une par une.</h3>

<h3><p style = "color : red">.shape</p>Cette  commande donne le nombre de lignes er de colonnes.Pour faire cour elle permt de connaitre la taille du dataset</h3>

In [60]:
taille = df.shape ## Donne moi la taille de df

taille

(3, 3)

<h3><p style = "color : red">.columns</p>Cette commande nous donne la liste des noms de colonnes.Elle permet de savoir quelle variable sont disponible
</h3>

In [61]:
colonnes = df.columns
colonnes   ##Renvoi les variables dispocnibcle par exemple dans notre cas nom, age , filiere

Index(['nom', 'age', 'Filiere'], dtype='object')

<h3><p style = "color : red">.dtypes</p>Cette comande donne le type de donnes de chaque 
    colones(entier, texte, decimal).Cette commande nous permet de reperer si une colonne x contient un type incorect(Exemple une date stockees comme texte </h3>.

In [62]:
# creer un nouveau dataset
Data = {
    'nom' : ['SAKPANI', 'PAGUI', 'DAMBE'],
    'Ages':[18, 'e', 19]
}

test = pd.DataFrame(Data)
test.dtypes

nom     object
Ages    object
dtype: object

<h2 align = "center" style ="color : red ">Exploration d'un dataset </h2>

In [64]:
Data = {
    "nom ": ["Sakpani", "Sambi", "Cahrlotte", "Dini", "Salomo", "Voloco", "Json","Kombate"],
    "Age" :[19, 13,15,20,29, 32,23,52],
    "Filiere": ["IA&BD", "GM", "IS", "GC", "GE", "MTH103","PHY100","PAD122"],
    "Telephone":[91129048, 90492300, 98786534, 70231232, 72440023,91129048, 90492300, 98786534],
    "code " :[80109, 1000,9080,4890,1009,8900,3405,3990],
    "Langage" :["Python", "C", "C++", "PHP","JAVA", "JAVASCRIPT", "C#","RUBY"],
    "Profession" :["Data Scientist", "Ing -IA", "ing-ML", "Devellopeur web", "Data Scientist", "Data Scientist", "Data engeneer", "Data Analyst"],
    "Entreprise":["OTR", "INSEED", "ANAC", "ARCEP", "ASECNA", "YAS TOGO", "BIA", "Orabank"]
}

base = pd.DataFrame(Data)
base ##Affichage de la dataset

,nom,Age,Filiere,Telephone,code,Langage,Profession,Entreprise
0,Sakpani,19,IA&BD,91129048,80109,Python,Data Scientist,OTR
1,Sambi,13,GM,90492300,1000,C,Ing -IA,INSEED
2,Cahrlotte,15,IS,98786534,9080,C++,ing ML,ANAC
3,Dini,20,GC,70231232,4890,PHP,Devellopeur web,ARCEP
4,Salomo,29,GE,72440023,1009,JAVA,Data Scientist,ASECNA
5,Voloco,32,MTH103,91129048,8900,JAVASCRIPT,Data Scientist,YAS TOGO
6,Json,23,PHY100,90492300,3405,C#,Data engeneer,BIA
7,Kombate,52,PAD122,98786534,3990,RUBY,Data Analyst,Orabank

<h3><p style = "color : blue"> 2.2 Explorer rapidement un dataFrame</p>Quand tu recois un vrai dataset(souvent des milliers de lignes), tu ne vas pas tout afficher d'un coup.Voici les outils pour l'explorer intelligemmnent.
</h3>

<h3><p style = "color : red">.head()</p>Cette commande affiche les premiere lignes du DataFrame (5 par defaut) </h3>

In [81]:
# ## la fonction prend en paramettre in entier qui va permettre de
# limiter la ligne ou on veut s'arrette.Pour cette ligne python affichera le nombre d'element
# par defaut dans la suite ,Je vais specifier pour bien explore

headBase = base.head()
headBase   ##On remarque que python a afficher les 5 premier lignes

,nom,Age,Filiere,Telephone,code,Langage,Profession,Entreprise
0,Sakpani,19,IA&BD,91129048,80109,Python,Data Scientist,OTR
1,Sambi,13,GM,90492300,1000,C,Ing -IA,INSEED
2,Cahrlotte,15,IS,98786534,9080,C++,ing ML,ANAC
3,Dini,20,GC,70231232,4890,PHP,Devellopeur web,ARCEP
4,Salomo,29,GE,72440023,1009,JAVA,Data Scientist,ASECNA

In [82]:
Donnes_Ligne1= base.head(0)

In [83]:
Donnes_Ligne1   ##On remarque la preier ligne affiche les variable du DataSet

Empty DataFrame
Columns: [nom , Age, Filiere, Telephone, code , Langage, Profession, Entreprise]
Index: []

In [84]:
Donne_Ligne2 = base.head(1)

In [85]:
Donne_Ligne2 ##Quand on entre 1 en parametree python affiche la premiere lignes de la dataset

      nom   Age Filiere  Telephone  code  Langage      Profession Entreprise
0  Sakpani   19   IA&BD   91129048  80109  Python  Data Scientist        OTR

 <h3><p style = "color : red">.tail()</p>Cette commande affiche les dernieres lignes du DataFrame (5 lignes  par defaut) </h3>

In [77]:
DernierLignes = base.tail()
DernierLignes  #affiche par defaut les 5 dernieres lignes de la dataSet

,nom,Age,Filiere,Telephone,code,Langage,Profession,Entreprise
3,Dini,20,GC,70231232,4890,PHP,Devellopeur web,ARCEP
4,Salomo,29,GE,72440023,1009,JAVA,Data Scientist,ASECNA
5,Voloco,32,MTH103,91129048,8900,JAVASCRIPT,Data Scientist,YAS TOGO
6,Json,23,PHY100,90492300,3405,C#,Data engeneer,BIA
7,Kombate,52,PAD122,98786534,3990,RUBY,Data Analyst,Orabank

In [79]:
derniere_Lignes2 = base.tail(1)
derniere_Lignes2   #Afficher le derniere ligne de la dataset

      nom   Age Filiere  Telephone  code  Langage    Profession Entreprise
7  Kombate   52  PAD122   98786534   3990    RUBY  Data Analyst    Orabank

 <h3><p style = "color : red">.info()</p>Cette commande permet d'afficher le resume techniqe de la DataFrame - nombres de lignes , nombres de colonnes, types de chaque colonnes, et nombrwe de valeurs non vide du dataSet</h3>

In [80]:
Affiche_Infos = base.info()
Affiche_Infos  ##Affichage des information du dataset

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   nom         8 non-null      object
 1   Age         8 non-null      int64
 2   Filiere     8 non-null      object
 3   Telephone   8 non-null      int64
 4   code        8 non-null      int64
 5   Langage     8 non-null      object
 6   Profession  8 non-null      object
 7   Entreprise  8 non-null      object
dtypes: int64(3), object(5)
memory usage: 644.0+ bytes

 <h3><p style = "color : red">.describe()</p>Cette commande Calcule automatiquement des statistiques descriptives(moyennes, ecart-types, min, max, quartiles ) pour toutes les colonnes </h3>

In [86]:
Statistiques = base.describe()
Statistiques

             Age     Telephone         code
count   8.000000  8.000000e+00      8.000000
mean   25.375000  8.793588e+07  14047.875000
std    12.546343  1.083983e+07  26869.553271
min    13.000000  7.023123e+07   1000.000000
25%    18.000000  8.597923e+07   2806.000000
50%    21.500000  9.081067e+07   4440.000000
75%    29.750000  9.304342e+07   8945.000000
max    52.000000  9.878653e+07  80109.000000

<h2 style = "color : blue">B. Organisation et explotation de données</h2>

<h3 style = "color:red">1. Charger des données depuis un fichier </h3>

<h4>Dans la vraie vie, on ne crées presque jamais un DataFrame à la main comme on l'a fait — tes données arrivent depuis un fichier (CSV, Excel, etc.).</h4>

 <h3><p style = "color : red">pd.read_csv()</p>Cette commande lit un fichier CSV (valeur separés par des virgules et le transrforme en DataFrame </h3>

In [92]:
= read_csv("nomFichier.csv") ## chargement d'un fichier csv
# df  Afficher

#Pour l'instant le fichier si "nomFichier" n'est pas creer donc si on essaye de charger un#fichier inexistarnt ou vide python
# va afficher une grosse erreur

In [ ]:
# Quelques parametres utiles a connaitre:
df = pd.read_csv('nomfichier.csv', sep = ';') # si le séparateur n'est pas une virgule 
df = pd.read_csv('nomfichier.csv', encoding = 'utf-8') #S'il y'a probleme d'accent
df = pd.read_csv('nomfichier.csv', nrows = 100) #Charger seulement 100 lignes (test rapide)