<h1 align="center" style="color:blue;">
📘 Formation à la bibliothèque Pandas : Manipulation et analyse de données
</h1>

<p align="center">
<b>Réalisé par :</b> SAKPANI Paguiyedou<br>
Étudiant en Licence Fondamentale – Sciences de l'Ingénieur<br>
Filière : Intelligence Artificielle & Big Data<br>
École Polytechnique de Lomé (EPL)
</p>

<h3 style="color:#1f77b4;">📖 Introduction</h3>

<p style="text-align:justify;">
Dans le domaine de la <strong>Data Science</strong>, les données proviennent de nombreuses sources (fichiers CSV, fichiers Excel, bases de données, API, etc.) et se présentent sous différentes formes. Afin de les exploiter efficacement, il est indispensable de disposer d'un outil capable de les importer, de les organiser, de les nettoyer, de les transformer et de les analyser.
</p>

<p style="text-align:justify;">
C'est précisément le rôle de la <strong>bibliothèque Pandas</strong>, l'une des bibliothèques les plus utilisées en Python pour la manipulation et l'analyse de données. Elle fournit des structures de données puissantes et intuitives qui permettent de travailler efficacement sur des jeux de données de toute taille.
</p>

<p style="text-align:justify; color:#c0392b;">
Le <strong>DataFrame</strong> est la structure de données principale de Pandas. Il permet de représenter les données sous la forme d'un tableau à deux dimensions, composé de lignes et de colonnes dont chacune possède un nom explicite. À l'image d'un tableau Excel ou d'une table d'une base de données, chaque colonne représente une variable et chaque ligne correspond à une observation (ou individu).
</p>

<p style="text-align:justify;">
Chaque colonne d'un <strong>DataFrame</strong> possède un type de données unique (<em>entier</em>, <em>réel</em>, <em>chaîne de caractères</em>, <em>date</em>, etc.), tandis que différentes colonnes peuvent contenir des types différents. Cette organisation rend les données faciles à manipuler et permet d'effectuer de nombreuses opérations telles que le filtrage, le tri, les calculs statistiques, la fusion de tableaux, le traitement des valeurs manquantes et la visualisation des données.
</p>

<p style="text-align:justify;">
Au cours de cette formation, nous découvrirons progressivement les principales fonctionnalités de Pandas afin d'acquérir les compétences nécessaires pour manipuler des données réelles et réaliser des analyses efficaces dans le cadre de projets de Data Science.
</p>

<h2 style ='color : blue'>A. Introduction et structures de données (Series, DataFrame)</h2>

<h3><p></p>1 . La Series</p>
<p><p style = "color : red">Definition :</p>une Series, c'est une colonne de données à une seule dimension. Chaque valeur est associée à une étiquette qu'on appelle un "index" — un peu comme une colonne Excel avec des numéros de ligne à gauche.<br style ="color : red" </p></h3>

In [1]:
import pandas as pd ##Importation de la librairie pandas

In [2]:
ages = pd.Series([19,24,45])

In [3]:
ages  ##Resultat

0    19
1    24
2    45
dtype: int64

In [4]:
##A gauche on a (0,1,2) , c'est lindex automatique.A droite , ce sont des valeurs .

In [8]:
ages =pd.Series([19,24,45], index = ["Sakapni", "Pagui", "Toto"]) ##Il faut note aussi que je peut choisir moi-memes les etiques de l'index

In [9]:
ages

Sakapni    19
Pagui      24
Toto       45
dtype: int64

In [ ]:
#Les series se comporte comme les dictionnaire en python =sauf qu'en python on parle de clee et vsleur pour la serie e=on parle de index

In [4]:
import pandas as pd

In [21]:

Dico= {
    "SAMI" :19,
    "ISERL" :20,
    "PADFREI" : 18,
    "SAKPANI":18,
    "Komblah" :10,
    "ERE" :3,
    "JO" : 8
} 
Dico  #Dictionnaire

{'SAMI': 19,
 'ISERL': 20,
 'PADFREI': 18,
 'SAKPANI': 18,
 'Komblah': 10,
 'ERE': 3,
 'JO': 8}

In [22]:
Dico_Series = pd.Series(Dico)
Dico_Series

SAMI       19
ISERL      20
PADFREI    18
SAKPANI    18
Komblah    10
ERE         3
JO          8
dtype: int64

In [23]:
##On peut aussi modifier , ajouter les element dans une serie cocmme un dictionnaire

In [24]:
Dico_Series["SAMI"]= 17 #Modification de la note de Sami

In [25]:
Dico_Series

SAMI       17
ISERL      20
PADFREI    18
SAKPANI    18
Komblah    10
ERE         3
JO          8
dtype: int64

In [26]:
# Ajout d'un element dans une series

In [27]:
Dico_Series["PAGUI"] = 19

In [28]:
Dico_Series

SAMI       17
ISERL      20
PADFREI    18
SAKPANI    18
Komblah    10
ERE         3
JO          8
PAGUI      19
dtype: int64

In [ ]:
## on peut aussi flitrer une Series

In [30]:
note_10_12 = Dico_Series[(Dico_Series >= 10) & (Dico_Series <=12)]
note_10_12  #Afficher les notes comcpries entre 10 et 12

Komblah    10
dtype: int64

In [31]:
note_10 = Dico_Series[(Dico_Series >= 10)] 
note_10  #nOTE >=10

SAMI       17
ISERL      20
PADFREI    18
SAKPANI    18
Komblah    10
PAGUI      19
dtype: int64

<h3><p style = "color : red"> 2. Le Data Frame</p><p><p  style = "color :red" >Définition :</p> un DataFrame, c'est un tableau à deux dimensions — plusieurs colonnes (donc plusieurs Series regroupées ensemble), avec des noms de colonnes et un index de lignes. C'est la structure centrale de Pandas.</p>

<p style = "color : red">Utilité :</p> c'est ce que tu utiliseras tout le temps en pratique, car un vrai dataset a toujours plusieurs colonnes (nom, âge, prime, type de contrat, etc.), pas une seule.</h3>

In [27]:
data = {
    'nom': ['Alice', 'Bob', 'Chloé'],
    'age': [25, 30, 35],
    'Filiere': ['IA', 'GC', 'GM']
}
df = pd.DataFrame(data)   ## ma premire fois de crrer un DataFrame en avec la librairie pandas .Quelle joie.
df

     nom  age Filiere
0  Alice   25      IA
1    Bob   30      GC
2  Chloé   35      GM

<h3><p style = "color : blue"> 2.1 -Comprendre la structure d'un DataFrame</p>Une fois que tu as un DataFrame, tu veux souvent savoir ce qu'il contient sans tout afficher. Voici les commandes de base, une par une.</h3>

<h3><p style = "color : red">.shape</p>Cette  commande donne le nombre de lignes er de colonnes.Pour faire cour elle permt de connaitre la taille du dataset</h3>

In [60]:
taille = df.shape ## Donne moi la taille de df

taille

(3, 3)

<h3><p style = "color : red">.columns</p>Cette commande nous donne la liste des noms de colonnes.Elle permet de savoir quelle variable sont disponible
</h3>

In [61]:
colonnes = df.columns
colonnes   ##Renvoi les variables dispocnibcle par exemple dans notre cas nom, age , filiere

Index(['nom', 'age', 'Filiere'], dtype='object')

<h3><p style = "color : red">.dtypes</p>Cette comande donne le type de donnes de chaque 
    colones(entier, texte, decimal).Cette commande nous permet de reperer si une colonne x contient un type incorect(Exemple une date stockees comme texte </h3>.

In [62]:
# creer un nouveau dataset
Data = {
    'nom' : ['SAKPANI', 'PAGUI', 'DAMBE'],
    'Ages':[18, 'e', 19]
}

test = pd.DataFrame(Data)
test.dtypes

nom     object
Ages    object
dtype: object

<h2 align = "center" style ="color : red ">Exploration d'un dataset </h2>

In [64]:
Data = {
    "nom ": ["Sakpani", "Sambi", "Cahrlotte", "Dini", "Salomo", "Voloco", "Json","Kombate"],
    "Age" :[19, 13,15,20,29, 32,23,52],
    "Filiere": ["IA&BD", "GM", "IS", "GC", "GE", "MTH103","PHY100","PAD122"],
    "Telephone":[91129048, 90492300, 98786534, 70231232, 72440023,91129048, 90492300, 98786534],
    "code " :[80109, 1000,9080,4890,1009,8900,3405,3990],
    "Langage" :["Python", "C", "C++", "PHP","JAVA", "JAVASCRIPT", "C#","RUBY"],
    "Profession" :["Data Scientist", "Ing -IA", "ing-ML", "Devellopeur web", "Data Scientist", "Data Scientist", "Data engeneer", "Data Analyst"],
    "Entreprise":["OTR", "INSEED", "ANAC", "ARCEP", "ASECNA", "YAS TOGO", "BIA", "Orabank"]
}

base = pd.DataFrame(Data)
base ##Affichage de la dataset

,nom,Age,Filiere,Telephone,code,Langage,Profession,Entreprise
0,Sakpani,19,IA&BD,91129048,80109,Python,Data Scientist,OTR
1,Sambi,13,GM,90492300,1000,C,Ing -IA,INSEED
2,Cahrlotte,15,IS,98786534,9080,C++,ing ML,ANAC
3,Dini,20,GC,70231232,4890,PHP,Devellopeur web,ARCEP
4,Salomo,29,GE,72440023,1009,JAVA,Data Scientist,ASECNA
5,Voloco,32,MTH103,91129048,8900,JAVASCRIPT,Data Scientist,YAS TOGO
6,Json,23,PHY100,90492300,3405,C#,Data engeneer,BIA
7,Kombate,52,PAD122,98786534,3990,RUBY,Data Analyst,Orabank

<h3><p style = "color : blue"> 2.2 Explorer rapidement un dataFrame</p>Quand tu recois un vrai dataset(souvent des milliers de lignes), tu ne vas pas tout afficher d'un coup.Voici les outils pour l'explorer intelligemmnent.
</h3>

<h3><p style = "color : red">.head()</p>Cette commande affiche les premiere lignes du DataFrame (5 par defaut) </h3>

In [81]:
# ## la fonction prend en paramettre in entier qui va permettre de
# limiter la ligne ou on veut s'arrette.Pour cette ligne python affichera le nombre d'element
# par defaut dans la suite ,Je vais specifier pour bien explore

headBase = base.head()
headBase   ##On remarque que python a afficher les 5 premieres lignes

,nom,Age,Filiere,Telephone,code,Langage,Profession,Entreprise
0,Sakpani,19,IA&BD,91129048,80109,Python,Data Scientist,OTR
1,Sambi,13,GM,90492300,1000,C,Ing -IA,INSEED
2,Cahrlotte,15,IS,98786534,9080,C++,ing ML,ANAC
3,Dini,20,GC,70231232,4890,PHP,Devellopeur web,ARCEP
4,Salomo,29,GE,72440023,1009,JAVA,Data Scientist,ASECNA

In [82]:
Donnes_Ligne1= base.head(0)

In [83]:
Donnes_Ligne1   ##On remarque la premireer ligne affiche les variable du DataSet :ligne 0

Empty DataFrame
Columns: [nom , Age, Filiere, Telephone, code , Langage, Profession, Entreprise]
Index: []

In [84]:
Donne_Ligne2 = base.head(1)

In [85]:
Donne_Ligne2 ##Quand on entre 1 en parametree python affiche la premiere lignes de la dataset : Ligne 1

      nom   Age Filiere  Telephone  code  Langage      Profession Entreprise
0  Sakpani   19   IA&BD   91129048  80109  Python  Data Scientist        OTR

 <h3><p style = "color : red">.tail()</p>Cette commande affiche les dernieres lignes du DataFrame (5 lignes  par defaut) </h3>

In [77]:
DernierLignes = base.tail()
DernierLignes  #affiche par defaut les 5 dernieres lignes de la dataSet

,nom,Age,Filiere,Telephone,code,Langage,Profession,Entreprise
3,Dini,20,GC,70231232,4890,PHP,Devellopeur web,ARCEP
4,Salomo,29,GE,72440023,1009,JAVA,Data Scientist,ASECNA
5,Voloco,32,MTH103,91129048,8900,JAVASCRIPT,Data Scientist,YAS TOGO
6,Json,23,PHY100,90492300,3405,C#,Data engeneer,BIA
7,Kombate,52,PAD122,98786534,3990,RUBY,Data Analyst,Orabank

In [79]:
derniere_Lignes2 = base.tail(1)
derniere_Lignes2   #Afficher le derniere ligne de la dataset

      nom   Age Filiere  Telephone  code  Langage    Profession Entreprise
7  Kombate   52  PAD122   98786534   3990    RUBY  Data Analyst    Orabank

 <h3><p style = "color : red">.info()</p>Cette commande permet d'afficher le resume techniqe de la DataFrame - nombres de lignes , nombres de colonnes, types de chaque colonnes, et nombrwe de valeurs non vide du dataSet</h3>

In [80]:
Affiche_Infos = base.info()
Affiche_Infos  ##Affichage des information du dataset

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   nom         8 non-null      object
 1   Age         8 non-null      int64
 2   Filiere     8 non-null      object
 3   Telephone   8 non-null      int64
 4   code        8 non-null      int64
 5   Langage     8 non-null      object
 6   Profession  8 non-null      object
 7   Entreprise  8 non-null      object
dtypes: int64(3), object(5)
memory usage: 644.0+ bytes

 <h3><p style = "color : red">.describe()</p>Cette commande Calcule automatiquement des statistiques descriptives(moyennes, ecart-types, min, max, quartiles ) pour toutes les colonnes </h3>

In [86]:
Statistiques = base.describe()
Statistiques

             Age     Telephone         code
count   8.000000  8.000000e+00      8.000000
mean   25.375000  8.793588e+07  14047.875000
std    12.546343  1.083983e+07  26869.553271
min    13.000000  7.023123e+07   1000.000000
25%    18.000000  8.597923e+07   2806.000000
50%    21.500000  9.081067e+07   4440.000000
75%    29.750000  9.304342e+07   8945.000000
max    52.000000  9.878653e+07  80109.000000

<h2 style = "color : blue">B. Organisation et explotation de données</h2>

<h3 style = "color:red">1. Charger des données depuis un fichier </h3>

<h4>Dans la vraie vie, on ne crées presque jamais un DataFrame à la main comme on l'a fait — tes données arrivent depuis un fichier (CSV, Excel, etc.).</h4>

 <h4><p style = "color : red">pd.read_csv()</p>Cette commande lit un fichier CSV (valeur separés par des virgules et le transrforme en DataFrame </h4>

In [92]:
= read_csv("nomFichier.csv") ## chargement d'un fichier csv
# df  Afficher

#Pour l'instant le fichier si "nomFichier" n'est pas creer donc si on essaye de charger un#fichier inexistarnt ou vide python
# va afficher une grosse erreur

In [ ]:
# Quelques parametres utiles a connaitre:
df = pd.read_csv('nomfichier.csv', sep = ';') # si le séparateur n'est pas une virgule 
df = pd.read_csv('nomfichier.csv', encoding = 'utf-8') #S'il y'a probleme d'accent
df = pd.read_csv('nomfichier.csv', nrows = 100) #Charger seulement 100 lignes (test rapide)

 <h4><p style = "color : red">pd.read_excel()</p>Cette commande lit un fichier excel (<span style = "color : red ">.xlsx</span>) et le transrforme en DataFrame </h4>

In [3]:
 df = pd.read_excel("nomfichier.xlsx", sheet_name = "Feuille1")  ##Chargement d'un fichier Excel (.xlsx)

 <h4><p style = "color : red">pd.read_json()</p>Cette commande lit un fichier JSON et le transrforme en DataFrame. Il est utile quand les donnes viennent d'une API ou d'un export JSON. </h4>

In [6]:
df = pd.read_json("nomfichier.json") ##Chargement du fichier JSON

<h3 style = "color:red">2. Exporter des données </h3>

<h4><p style = "color : red">df.to_csv()</p>Cette commande sauvegarde un DataFrame dans un fichier (<span style = "color : red ">CSV</span>) </h4>

In [ ]:
df = pd.to_csv("nomfichier.csv", index = False) # index = False évite d'ajouter une colone de l'index inutile

<h3 style = "color:red">3. Vérifier les valeurs uniques d une colonne </h3>

 <h4><p style = "color : red">.unique()</p>Cette commande renvoi toutes les valeurs distinctes présentes dans une colonne.Permet de voir toutes les categories possible d'une variable  (ex : tous les types de contrats existans) </h4>

In [32]:
import pandas as pd

In [33]:
Data = {
    "nom ": ["Sakpani", "Sambi", "Cahrlotte", "Dini", "Salomo", "Voloco", "Json","Kombate"],
    "Age" :[19, 13,15,20,29, 32,23,52],
    "Filiere": ["IA&BD", "GM", "IS", "GC", "GE", "MTH103","PHY100","PAD122"],
    "Telephone":[91129048, 90492300, 98786534, 70231232, 72440023,91129048, 90492300, 98786534],
    "code " :[80109, 1000,9080,4890,1009,8900,3405,3990],
    "Langage" :["Python", "C", "C++", "PHP","JAVA", "JAVASCRIPT", "C#","RUBY"],
    "Profession" :["Data Scientist", "Ing -IA", "ing ML", "Devellopeur web", "Data Scientist", "Data Scientist", "Data engeneer", "Data Analyst"],
    "Entreprise":["OTR", "INSEED", "ANAC", "ARCEP", "ASECNA", "YAS TOGO", "BIA", "Orabank"],
    "Loisir" : ["Football", "Volley- ball", "Football", "Football", "Football", "Football", "Tenis", "Basket-ball"],
    "Disponible" :["NON", "OUI", "OUI", "OUI", "OUI", "OUI", "OUI", "NON"],
    "Niveau" :["Expert", "Junior", "Debutant", "Debutant", "Debutant", "Debutant", "Debutant", "Debutant"]
}

base = pd.DataFrame(Data)
base

,nom,Age,Filiere,Telephone,code,Langage,Profession,Entreprise,Loisir,Disponible,Niveau
0,Sakpani,19,IA&BD,91129048,80109,Python,Data Scientist,OTR,Football,NON,Expert
1,Sambi,13,GM,90492300,1000,C,Ing -IA,INSEED,Volley- ball,OUI,Junior
2,Cahrlotte,15,IS,98786534,9080,C++,ing ML,ANAC,Football,OUI,Debutant
3,Dini,20,GC,70231232,4890,PHP,Devellopeur web,ARCEP,Football,OUI,Debutant
4,Salomo,29,GE,72440023,1009,JAVA,Data Scientist,ASECNA,Football,OUI,Debutant
5,Voloco,32,MTH103,91129048,8900,JAVASCRIPT,Data Scientist,YAS TOGO,Football,OUI,Debutant
6,Json,23,PHY100,90492300,3405,C#,Data engeneer,BIA,Tenis,OUI,Debutant
7,Kombate,52,PAD122,98786534,3990,RUBY,Data Analyst,Orabank,Basket-ball,NON,Debutant

In [34]:
        # .unique()   ;  .nunique()   ;  value_counts()

<h2 style ='color : blue'>C. Sélection et filtrage</h2>

In [53]:
df=base
df

,nom,Age,Filiere,Telephone,code,Langage,Profession,Entreprise,Loisir,Disponible,Niveau
0,Sakpani,19,IA&BD,91129048,80109,Python,Data Scientist,OTR,Football,NON,Expert
1,Sambi,13,GM,90492300,1000,C,Ing -IA,INSEED,Volley- ball,OUI,Junior
2,Cahrlotte,15,IS,98786534,9080,C++,ing ML,ANAC,Football,OUI,Debutant
3,Dini,20,GC,70231232,4890,PHP,Devellopeur web,ARCEP,Football,OUI,Debutant
4,Salomo,29,GE,72440023,1009,JAVA,Data Scientist,ASECNA,Football,OUI,Debutant
5,Voloco,32,MTH103,91129048,8900,JAVASCRIPT,Data Scientist,YAS TOGO,Football,OUI,Debutant
6,Json,23,PHY100,90492300,3405,C#,Data engeneer,BIA,Tenis,OUI,Debutant
7,Kombate,52,PAD122,98786534,3990,RUBY,Data Analyst,Orabank,Basket-ball,NON,Debutant

<h3 style = "color:red">1. Sélection d' une colonne </h3>

<h4 style = "color:red">df['colone']</h4>

<p><span style = "color : red ">Definition:</span>Selectionne une seule colonne , renvoyée sous forme de Séries; cette commande permet d'acceder une variable précise pour l'analiser</p>

In [54]:
Langage = df['Langage']
Langage  #affiche la colonne des langages

0        Python
1             C
2           C++
3           PHP
4          JAVA
5    JAVASCRIPT
6            C#
7          RUBY
Name: Langage, dtype: object

In [56]:
# On peut aussi selection deux colones mais dans ce cas il faut utiliser une liste de liste comme ceci:

Info_2 = df[["Profession", "Langage"]]
Info_2

        Profession     Langage
0   Data Scientist      Python
1          Ing -IA           C
2           ing ML         C++
3  Devellopeur web         PHP
4   Data Scientist        JAVA
5   Data Scientist  JAVASCRIPT
6    Data engeneer          C#
7     Data Analyst        RUBY

<h3 style = "color:red">2. Sélection des lignes avec <spans style = "color : blue">.loc[]</span> et <spans style = "color : blue">.iloc[]</span></h3>

#### Loc selectione des lignes /colonnes par label (nom d'index, nom de coloncne)

In [65]:
df.loc[0]   ##Avec loc

nom                  Sakpani
Age                       19
Filiere                IA&BD
Telephone           91129048
code                   80109
Langage               Python
Profession    Data Scientist
Entreprise               OTR
Loisir              Football
Disponible               NON
Niveau                Expert
Name: 0, dtype: object

In [67]:
df.loc[0 : 2]  ##La ligne de 0 a 2 inclus

,nom,Age,Filiere,Telephone,code,Langage,Profession,Entreprise,Loisir,Disponible,Niveau
0,Sakpani,19,IA&BD,91129048,80109,Python,Data Scientist,OTR,Football,NON,Expert
1,Sambi,13,GM,90492300,1000,C,Ing -IA,INSEED,Volley- ball,OUI,Junior
2,Cahrlotte,15,IS,98786534,9080,C++,ing ML,ANAC,Football,OUI,Debutant

In [68]:
df.loc[0, "Age"]  ##Element qqui est suur la ligne 0 de la colonne Age

np.int64(19)

In [70]:
df.loc[0:2, ["Profession", "Langage"]] #Element qui se trouve dans la colonne de proffession et et Langage qui sont sur la ligne 0 et 2 inclus

       Profession Langage
0  Data Scientist  Python
1         Ing -IA       C
2          ing ML     C++

#### ***.iloc[]*** Selectionne les ligns/colonnes par position numeriques(Comme des indices d'une liste de python)

In [71]:
df.iloc[0]   ##Selection la premiee line (position 0)

nom                  Sakpani
Age                       19
Filiere                IA&BD
Telephone           91129048
code                   80109
Langage               Python
Profession    Data Scientist
Entreprise               OTR
Loisir              Football
Disponible               NON
Niveau                Expert
Name: 0, dtype: object

In [72]:
df.iloc[3]  ##Selectionne la 3eme ligne

nom                      Dini
Age                        20
Filiere                    GC
Telephone            70231232
code                     4890
Langage                   PHP
Profession    Devellopeur web
Entreprise              ARCEP
Loisir               Football
Disponible                OUI
Niveau               Debutant
Name: 3, dtype: object

In [73]:
df.iloc[0:2] ##Les deux premiere lignes (0 linclus, 2 exclus)

,nom,Age,Filiere,Telephone,code,Langage,Profession,Entreprise,Loisir,Disponible,Niveau
0,Sakpani,19,IA&BD,91129048,80109,Python,Data Scientist,OTR,Football,NON,Expert
1,Sambi,13,GM,90492300,1000,C,Ing -IA,INSEED,Volley- ball,OUI,Junior

In [76]:
df.iloc[0, 9]  ## ligne 0 et colone a la position 9

##Cette methode permet de selectionner un element ecacte

'NON'

<h3 style = "color:red">3. Filtrer avec des conditions </h3>

In [109]:
Etudiant = {
    "Nom" : ["SAKPANI", "PAGUI", "HRO", "DPYRO", "gedon"],
    "Filiere" :["IA", "GC", "GE", "LT", "GM"],
    "MATHS" :[18,14,10,2,13],
    "PHY" :[14,13,4,0,9]
}
df = pd.DataFrame(Etudiant)
df

       Nom Filiere  MATHS  PHY
0  SAKPANI      IA     18   14
1    PAGUI      GC     14   13
2      HRO      GE     10    4
3    DPYRO      LT      2    0
4    gedon      GM     13    9

In [110]:
df[df["MATHS"]>10]  ##Selectionne les ligne qui respecte la conditon MATHS>10

       Nom Filiere  MATHS  PHY
0  SAKPANI      IA     18   14
1    PAGUI      GC     14   13
4    gedon      GM     13    9

In [111]:
df

       Nom Filiere  MATHS  PHY
0  SAKPANI      IA     18   14
1    PAGUI      GC     14   13
2      HRO      GE     10    4
3    DPYRO      LT      2    0
4    gedon      GM     13    9

In [112]:
df[df["PHY"] < 10]   ###AFFICHE LES DONNES SELON LA CONDITION PHY >10

     Nom Filiere  MATHS  PHY
2    HRO      GE     10    4
3  DPYRO      LT      2    0
4  gedon      GM     13    9

In [113]:
df[(df["MATHS"] > 10) & (df["PHY"] >10)]   ## Affiche lese etudiant qui on 10 de plus en physique et msths

       Nom Filiere  MATHS  PHY
0  SAKPANI      IA     18   14
1    PAGUI      GC     14   13

In [114]:
df["moyenne"] = (df["MATHS"] + df["PHY"])/2  #ajout de la moyenne dans le dataSet

In [115]:
df

       Nom Filiere  MATHS  PHY  moyenne
0  SAKPANI      IA     18   14     16.0
1    PAGUI      GC     14   13     13.5
2      HRO      GE     10    4      7.0
3    DPYRO      LT      2    0      1.0
4    gedon      GM     13    9     11.0

In [116]:
df[df["moyenne"]<10]  ##Affiche les etudiant ayant otenu des moyenne inf a 10

     Nom Filiere  MATHS  PHY  moyenne
2    HRO      GE     10    4      7.0
3  DPYRO      LT      2    0      1.0

<h4 style = "color:red">.isin()</h4> 
<p>Cette fonction permet de verifier si une valeur appartient a une liste donnee</p>

In [117]:
df[df["Filiere"].isin(["LT"])]  ## RECHERCHE LA FILIERE LT DANS FILIERE

     Nom Filiere  MATHS  PHY  moyenne
3  DPYRO      LT      2    0      1.0

In [118]:
df[df["Filiere"].isin(["KO", "LT"])]

     Nom Filiere  MATHS  PHY  moyenne
3  DPYRO      LT      2    0      1.0

<h2 style ='color : blue'>D . Netoyer de donnees</h2>

<h3 style = "color:red">3. Detecter les valeurs manquantes </h3>