In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("clients_assurance.csv")
df.head()

,id_client,nom,age,type_contrat,date_contrat,region,prime,nb_sinistres,montant_sinistres
0,100,Client_100,35.0,auto,2022-04-23,Savanes,324.63,3,810.05
1,298,Client_298,57.0,MOTO,2020-04-05,Plateaux,172.37,0,0.00
2,90,Client_90,65.0,habitation,2020-08-03,Plateaux,179.38,1,612.00
3,31,Client_31,NaN,auto,2021-02-05,Savanes,245.67,0,0.00
4,236,Client_236,69.0,habitation,2021-12-23,Maritime,130.21,1,567.57

In [3]:
df.info() ##Analyse des types de donnes du dataset

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 305 entries, 0 to 304
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id_client          305 non-null    int64
 1   nom                305 non-null    object
 2   age                293 non-null    float64
 3   type_contrat       305 non-null    object
 4   date_contrat       305 non-null    object
 5   region             299 non-null    object
 6   prime              296 non-null    float64
 7   nb_sinistres       305 non-null    int64
 8   montant_sinistres  305 non-null    float64
dtypes: float64(3), int64(2), object(4)
memory usage: 21.6+ KB

In [4]:
# """ D'apres les infos : sur 305:
#   - ages a 293 element qui ne sont pas null donc le reste sont des element manquant donc a corriger
#   - Pareil pour region 299 objet non null sur 305
#   - prime 293 elememt non nul sur 305 """

In [24]:
##Verifions plus precisement les element manquant en utilisant .isnull() et et isnull().sum()

df.isnull().head()

,id_client,nom,age,type_contrat,date_contrat,region,prime,nb_sinistres,montant_sinistres
0,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False

In [6]:
# .isnull() nous icnddique pour les partie visible des false hors .infos a trouver des element
# maquant dans le dataSet , il faut comprendre les elemen manqant se trouver a l'interieur c 'cest pourquoi
# fixons des intervales pocur essayer d''explorer voir avec la methode loc[] ou iloc[]
df.loc[50: 100]

,id_client,nom,age,type_contrat,date_contrat,region,prime,nb_sinistres,montant_sinistres
50,12,Client_12,28.0,moto,2024-12-07,Plateaux,160.48,0,0.00
51,165,Client_165,43.0,habitation,2022-09-09,Maritime,76.77,0,0.00
52,99,Client_99,62.0,auto,2020-11-19,Plateaux,267.23,0,0.00
53,271,Client_271,41.0,habitation,2020-06-10,Kara,163.14,0,0.00
54,290,Client_290,20.0,habitation,2023-06-06,Maritime,260.85,3,2271.66
55,177,Client_177,40.0,moto,2023-12-30,Centrale,111.38,0,0.00
56,174,Client_174,21.0,habitation,2023-08-25,Kara,292.50,1,982.79
57,95,Client_95,74.0,habitation,2024-07-29,NaN,99.96,1,487.38
58,162,Client_162,26.0,sante,2024-07-03,Savanes,168.78,0,0.00
59,218,Client_218,25.0,habitation,2023-10-16,Maritime,NaN,1,800.25
60,92,Client_92,25.0,AUTO,2024-09-15,Kara,304.88,0,0.00
61,273,Client_273,69.0,auto,2020-03-27,Centrale,336.07,1,1457.56
62,107,Client_107,58.0,habitation,2023-08-08,Centrale,237.64,0,0.00
63,11,Client_11,28.0,auto,2023-10-04,Kara,321.10,1,373.09
64,154,Client_154,20.0,auto,2024-10-15,Centrale,473.89,1,1214.52
65,78,Client_78,59.0,auto,2023-07-01,Centrale,392.12,0,0.00
66,24,Client_24,47.0,moto,2023-12-04,Savanes,151.54,1,785.16
67,128,Client_128,59.0,moto,2023-05-18,Maritime,102.55,0,0.00
68,142,Client_142,54.0,AUTO,2020-05-06,Maritime,364.56,0,0.00
69,129,Client_129,56.0,habitation,2022-09-11,Kara,253.91,0,0.00
70,207,Client_207,50.0,auto,2020-10-11,Maritime,284.36,1,414.88
71,164,Client_164,32.0,auto,2023-04-20,Savanes,307.10,2,1446.05
72,204,Client_204,45.0,auto,2024-03-04,Plateaux,224.30,0,0.00
73,202,Client_202,28.0,habitation,2023-04-18,Maritime,184.49,0,0.00
74,55,Client_55,31.0,habitation,2021-08-01,Kara,75.81,0,0.00
75,5,Client_5,60.0,habitation,2024-04-19,Maritime,125.86,0,0.00
76,157,Client_157,43.0,auto,2024-11-27,Savanes,318.74,0,0.00
77,105,Client_105,42.0,habitation,2021-09-18,Savanes,147.32,0,0.00
78,194,Client_194,70.0,auto,2022-07-27,Centrale,270.30,0,0.00
79,171,Client_171,66.0,auto,2021-10-22,Savanes,292.76,0,0.00
80,216,Client_216,56.0,habitation,2022-04-28,Kara,169.67,0,0.00
81,85,Client_85,51.0,auto,2023-02-15,NaN,332.19,0,0.00
82,25,Client_25,55.0,sante,2021-07-27,Maritime,96.63,1,495.05
83,284,Client_284,46.0,habitation,2021-03-18,Kara,104.14,0,0.00
84,115,Client_115,41.0,auto,2021-07-03,Centrale,216.80,1,1166.45
85,155,Client_155,18.0,auto,2022-02-17,Centrale,444.87,2,964.74
86,21,Client_21,19.0,auto,2022-04-30,Kara,435.80,0,0.00
87,29,Client_29,29.0,moto,2022-12-01,Maritime,184.79,1,337.40
88,132,Client_132,NaN,auto,2024-06-27,Plateaux,389.15,1,604.21
89,173,Client_173,49.0,habitation,2022-08-26,Maritime,147.24,1,979.18
90,72,Client_72,67.0,auto,2023-01-25,Savanes,391.94,1,877.00
91,283,Client_283,33.0,sante,2022-01-28,Plateaux,125.62,0,0.00
92,228,Client_228,71.0,auto,2020-11-22,Savanes,345.07,0,0.00
93,110,Client_110,62.0,moto,2020-03-09,Kara,206.56,0,0.00
94,65,Client_65,61.0,sante,2021-04-22,Maritime,79.81,0,0.00
95,15,Client_15,53.0,sante,2020-09-26,Kara,131.66,0,0.00
96,131,Client_131,45.0,auto,2024-07-04,Plateaux,272.89,0,0.00
97,152,Client_152,64.0,habitation,2023-08-12,Savanes,123.62,0,0.00
98,19,Client_19,39.0,sante,2023-04-03,Kara,187.99,0,0.00
99,86,Client_86,27.0,auto,2022-03-16,Plateaux,337.21,0,0.00
100,214,Client_214,58.0,auto,2022-12-08,Maritime,271.84,1,272.98

In [7]:
# ##Entre [50 , 100] si vous explorer tres bien dans le dataframe on voit 
# des mots "NAN " c'est pour indique qu'il y;a un eleement manquant  cet endtroit 

# On peut bien voir dans la colonne region et prime

In [8]:
##Apres cette exploration j'ai quand meme une envie d'explorer de compter plus precisement les element manquant 
df.isnull().sum()

id_client             0
nom                   0
age                  12
type_contrat          0
date_contrat          0
region                6
prime                 9
nb_sinistres          0
montant_sinistres     0
dtype: int64

In [9]:
# ##I Donc j' en sais plus precisement le nombbre d'element manquant pour chaqsue colonnes.
# .A retenir :
#   - .info() nous donne le nombre totale d'element non nul pour chaques colone 
#   - .isnull().sum()  nous donne exactement le nonmbre d'element nul pour chaque colonne  (total - total_Non_nul)

In [10]:



# ##Maintenant on ne peut pas laisser les element null Comme cela on doit trouver un moyen de les remplacer :

#    - dans notre cas region a des NAN : je vais remplacer par (inconnues)  car  c'est un string
#    - prime contient des float je vais remplaceer les element manquant par la madiane  de la colonne
#    - Pour l'age je vais remplacer par la moyenne de tout les ages de la colonne

In [11]:
df["region"] = df["region"].fillna("inconue")   ##complete les case manquante de region par inconneue

In [12]:
##Verification  avec .isnull.sum()
df.isnull().sum()

id_client             0
nom                   0
age                  12
type_contrat          0
date_contrat          0
region                0
prime                 9
nb_sinistres          0
montant_sinistres     0
dtype: int64

In [13]:
#    On remarque que region est redevenu 0 donc pus de case sans element rexplorons le dataFrame entre [50 et 100] voir 

df.loc[50 :100]  ## On voit dans certains case c'est ecrit inconnue donc fil na a fonctionner

,id_client,nom,age,type_contrat,date_contrat,region,prime,nb_sinistres,montant_sinistres
50,12,Client_12,28.0,moto,2024-12-07,Plateaux,160.48,0,0.00
51,165,Client_165,43.0,habitation,2022-09-09,Maritime,76.77,0,0.00
52,99,Client_99,62.0,auto,2020-11-19,Plateaux,267.23,0,0.00
53,271,Client_271,41.0,habitation,2020-06-10,Kara,163.14,0,0.00
54,290,Client_290,20.0,habitation,2023-06-06,Maritime,260.85,3,2271.66
55,177,Client_177,40.0,moto,2023-12-30,Centrale,111.38,0,0.00
56,174,Client_174,21.0,habitation,2023-08-25,Kara,292.50,1,982.79
57,95,Client_95,74.0,habitation,2024-07-29,inconue,99.96,1,487.38
58,162,Client_162,26.0,sante,2024-07-03,Savanes,168.78,0,0.00
59,218,Client_218,25.0,habitation,2023-10-16,Maritime,NaN,1,800.25
60,92,Client_92,25.0,AUTO,2024-09-15,Kara,304.88,0,0.00
61,273,Client_273,69.0,auto,2020-03-27,Centrale,336.07,1,1457.56
62,107,Client_107,58.0,habitation,2023-08-08,Centrale,237.64,0,0.00
63,11,Client_11,28.0,auto,2023-10-04,Kara,321.10,1,373.09
64,154,Client_154,20.0,auto,2024-10-15,Centrale,473.89,1,1214.52
65,78,Client_78,59.0,auto,2023-07-01,Centrale,392.12,0,0.00
66,24,Client_24,47.0,moto,2023-12-04,Savanes,151.54,1,785.16
67,128,Client_128,59.0,moto,2023-05-18,Maritime,102.55,0,0.00
68,142,Client_142,54.0,AUTO,2020-05-06,Maritime,364.56,0,0.00
69,129,Client_129,56.0,habitation,2022-09-11,Kara,253.91,0,0.00
70,207,Client_207,50.0,auto,2020-10-11,Maritime,284.36,1,414.88
71,164,Client_164,32.0,auto,2023-04-20,Savanes,307.10,2,1446.05
72,204,Client_204,45.0,auto,2024-03-04,Plateaux,224.30,0,0.00
73,202,Client_202,28.0,habitation,2023-04-18,Maritime,184.49,0,0.00
74,55,Client_55,31.0,habitation,2021-08-01,Kara,75.81,0,0.00
75,5,Client_5,60.0,habitation,2024-04-19,Maritime,125.86,0,0.00
76,157,Client_157,43.0,auto,2024-11-27,Savanes,318.74,0,0.00
77,105,Client_105,42.0,habitation,2021-09-18,Savanes,147.32,0,0.00
78,194,Client_194,70.0,auto,2022-07-27,Centrale,270.30,0,0.00
79,171,Client_171,66.0,auto,2021-10-22,Savanes,292.76,0,0.00
80,216,Client_216,56.0,habitation,2022-04-28,Kara,169.67,0,0.00
81,85,Client_85,51.0,auto,2023-02-15,inconue,332.19,0,0.00
82,25,Client_25,55.0,sante,2021-07-27,Maritime,96.63,1,495.05
83,284,Client_284,46.0,habitation,2021-03-18,Kara,104.14,0,0.00
84,115,Client_115,41.0,auto,2021-07-03,Centrale,216.80,1,1166.45
85,155,Client_155,18.0,auto,2022-02-17,Centrale,444.87,2,964.74
86,21,Client_21,19.0,auto,2022-04-30,Kara,435.80,0,0.00
87,29,Client_29,29.0,moto,2022-12-01,Maritime,184.79,1,337.40
88,132,Client_132,NaN,auto,2024-06-27,Plateaux,389.15,1,604.21
89,173,Client_173,49.0,habitation,2022-08-26,Maritime,147.24,1,979.18
90,72,Client_72,67.0,auto,2023-01-25,Savanes,391.94,1,877.00
91,283,Client_283,33.0,sante,2022-01-28,Plateaux,125.62,0,0.00
92,228,Client_228,71.0,auto,2020-11-22,Savanes,345.07,0,0.00
93,110,Client_110,62.0,moto,2020-03-09,Kara,206.56,0,0.00
94,65,Client_65,61.0,sante,2021-04-22,Maritime,79.81,0,0.00
95,15,Client_15,53.0,sante,2020-09-26,Kara,131.66,0,0.00
96,131,Client_131,45.0,auto,2024-07-04,Plateaux,272.89,0,0.00
97,152,Client_152,64.0,habitation,2023-08-12,Savanes,123.62,0,0.00
98,19,Client_19,39.0,sante,2023-04-03,Kara,187.99,0,0.00
99,86,Client_86,27.0,auto,2022-03-16,Plateaux,337.21,0,0.00
100,214,Client_214,58.0,auto,2022-12-08,Maritime,271.84,1,272.98

In [14]:
##Corection des case manquante de l'age .On remplace par la moyenne des ages

df["age"] = df["age"].fillna(df["age"].mean())

In [15]:
df.isnull().sum()  ##On trouve 0 pour age  donc la methode a fonctionner il ne reste plus que pour prime

id_client            0
nom                  0
age                  0
type_contrat         0
date_contrat         0
region               0
prime                9
nb_sinistres         0
montant_sinistres    0
dtype: int64

In [16]:
##Correction des NAN DE PRIME PAR LA MEDIAN

df["prime"] = df["prime"].fillna(df["prime"].median())

In [17]:
df.isnull().sum()

id_client            0
nom                  0
age                  0
type_contrat         0
date_contrat         0
region               0
prime                0
nb_sinistres         0
montant_sinistres    0
dtype: int64

In [18]:
df["type_contrat"].unique()

array(['auto', 'MOTO', 'habitation', 'sante', 'moto', 'AUTO',
       'HABITATION'], dtype=object)

In [19]:
df["type_contrat"].nunique()

7

In [20]:


# ##  En appliquant la metode type contrat on tombe sur ces donnes : (auto, AUTO) , (MOTO, moto) ;  (HABITATION, habitation)
# Miniscule t majiscule sont deux chose differentes en python , certainnement c'est une erreur de saisies lors du collecte de donnes donc 
# de ce fait voila l'importance de .unique (poUR SOLUTION JE VAIS RECONVERTIRR TOUT LES NOM EN MINISCULE )

df["type_contrat"] = df["type_contrat"].str.lower()   # Convertir en miniscule

In [21]:
df["type_contrat"].unique()

array(['auto', 'moto', 'habitation', 'sante'], dtype=object)

In [22]:
df["type_contrat"].nunique()

4

In [23]:
df.to_csv("fichier_netoyee.csv", index =  False)