In [1]:
import numpy as  np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn  as sns

In [2]:
# Importation des fichier csv 

client_id = pd.read_csv("data/clients.csv") # Information du client

catalogue_produit = pd.read_csv("data/produits.csv")

commande_clients_passe = pd.read_csv("data/commandes.csv") #Importation du fichier contenant les commandes de l'annees passe (2025)

fournisseurs = pd.read_csv("data/fournisseurs.csv")  ## Fichier contennant les infos des fournisseurs

avis_clients = pd.read_csv("data/avis.csv")  # Importation du fichier contenant les avis des clients apres livraison

### 1-) Analyse du fichier contenant les infos de chacuns de nos clients

In [3]:
client_id.head()

   client_id             nom   age sexe     ville date_inscription   segment
0          1     Kodjo Adjei  24.0    M   Kpalimé       2025-08-10   Nouveau
1          2     Dede Agbeko  20.0    M     Lomé        23/09/2023  Régulier
2          3  Akpene Tchassa  29.0    F   Dapaong       2025-12-11   Nouveau
3          4     Afi Tchassa  39.0    M   kpalime       2023-07-11       VIP
4          5     Sena Sossou  19.0    M  Atakpamé       07/05/2022  Régulier

In [4]:
client_id.tail()

     client_id            nom   age sexe     ville date_inscription   segment
256        257   Kodjo Agbeko  26.0    F      kara       2022-06-05   Nouveau
257        258    Essi Sossou  33.0    M   kpalime       19/02/2025       NaN
258        259    Afi Tchassa  21.0    F  Atakpamé       06/10/2022  Régulier
259        260     Sena Adjei  33.0    M      KARA       2023-11-25       VIP
260         11  Kekeli Dossou  20.0    F    Sokodé       24/07/2022  Régulier

In [5]:
client_id.shape[0] # Nombre total de lignes

261

In [6]:
client_id.info() # verification des types de donnees et valeurs manquantes

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 261 entries, 0 to 260
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   client_id         261 non-null    int64
 1   nom               261 non-null    object
 2   age               249 non-null    float64
 3   sexe              261 non-null    object
 4   ville             261 non-null    object
 5   date_inscription  261 non-null    object
 6   segment           251 non-null    object
dtypes: float64(1), int64(1), object(5)
memory usage: 14.4+ KB

In [7]:
client_id.isnull().sum()  # compteur des valeurs manquantes

client_id            0
nom                  0
age                 12
sexe                 0
ville                0
date_inscription     0
segment             10
dtype: int64

In [8]:
client_id["age"] = client_id["age"].fillna(client_id["age"].median()) #Remplacement des valeur manquantes par la mediane
client_id.isnull().sum()

client_id            0
nom                  0
age                  0
sexe                 0
ville                0
date_inscription     0
segment             10
dtype: int64

In [9]:
client_id["age"] = client_id["age"].astype(int) # Correction du type d'age DE FLOAT EN  INTEGER

In [10]:
client_id.info() #

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 261 entries, 0 to 260
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   client_id         261 non-null    int64
 1   nom               261 non-null    object
 2   age               261 non-null    int64
 3   sexe              261 non-null    object
 4   ville             261 non-null    object
 5   date_inscription  261 non-null    object
 6   segment           251 non-null    object
dtypes: int64(2), object(5)
memory usage: 14.4+ KB

-  Correction des valeur **manquantes sur la colonne segment**

In [11]:
client_id["segment"] = client_id["segment"].fillna("inconnue") # Remplacer les valeurs manquantes par *Inconnue*

In [12]:
client_id.isnull().sum()

client_id           0
nom                 0
age                 0
sexe                0
ville               0
date_inscription    0
segment             0
dtype: int64

- Verification des doublons

In [13]:
client_id.duplicated().sum()

np.int64(1)

Pas de doucblocn dans ce dataset

### 2-)Analyse du fichier contenant les produits de l'entreprise

In [14]:
catalogue_produit.head()

,product_id,category,brand,cost_price,list_price,stock_quantity,supplier_id
0,1,Cyclisme,Vela,41.0,95.5,333,2
1,2,Running,Kaito,40.1,56.3,199,5
2,3,Running,Atlas,24.2,42.8,136,2
3,4,Yoga,Kaito,23.4,46.8,233,4
4,5,Basketball,Prime,36.9,79.2,136,6

In [15]:
catalogue_produit.tail()

,product_id,category,brand,cost_price,list_price,stock_quantity,supplier_id
86,87,Yoga,Nova,44.8,NaN,101,6
87,88,Basketball,Kaito,21.4,35.7,205,1
88,89,Football,Nova,25.6,39.7,67,2
89,90,Basketball,Prime,24.9,40.3,65,5
90,4,Yoga,Kaito,23.4,46.8,238,4

In [16]:
catalogue_produit.shape[0] # Nombre de licgne de ce dataset

91

In [22]:
catalogue_produit = catalogue_produit.rename({"product_id":"id_produit",
                                              "category":  "categorie_sport",
                                              "brand" :"marque",
                                              "cost_price" : "prix_achat",
                                              "list_price" : "prix_vente",
                                              "stock_quantity" : "stock_disponible",
                                              "supplier_id" : "ref_fournisseur"
                                              }, axis = 1)  
# Renomons les variables du dataset

In [21]:
catalogue_produit.head()

,id_produit,categorie_sport,marque,prix_achat,prix_vente,stock_disponible,ref_fournisseur
0,1,Cyclisme,Vela,41.0,95.5,333,2
1,2,Running,Kaito,40.1,56.3,199,5
2,3,Running,Atlas,24.2,42.8,136,2
3,4,Yoga,Kaito,23.4,46.8,233,4
4,5,Basketball,Prime,36.9,79.2,136,6

In [24]:
catalogue_produit["categorie_sport"].value_counts()

categorie_sport
Cyclisme       16
Football       16
Running        14
Yoga           14
Fitness        10
Basketball      9
BASKETBALL      2
CYCLISME        2
FOOTBALL        2
football        1
running         1
fitness         1
yoga            1
basketball      1
cyclisme        1
Name: count, dtype: int64

In [25]:
catalogue_produit["marque"].value_counts()

marque
Prime     19
Nova      18
Atlas     17
Kaito     15
Vela      13
Fortis     9
Name: count, dtype: int64

- Correction des valeurs manquantes

In [23]:
catalogue_produit.isnull().sum()

id_produit          0
categorie_sport     0
marque              0
prix_achat          0
prix_vente          5
stock_disponible    0
ref_fournisseur     0
dtype: int64