In [1]:
import numpy as  np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn  as sns

In [2]:
# Importation des fichier csv 

client_id = pd.read_csv("data/clients.csv") # Information du client

produit = pd.read_csv("data/produits.csv")

commande_pass = pd.read_csv("data/commandes.csv") #Importation du fichier contenant les commandes de l'annees passe (2025)

fournisseurs = pd.read_csv("data/fournisseurs.csv")  ## Fichier contennant les infos des fournisseurs

avis_clients = pd.read_csv("data/avis.csv")  # Importation du fichier contenant les avis des clients apres livraison

### 1-) Analyse du fichier contenant les infos de chacuns de nos clients

In [3]:
client_id.head()

   client_id             nom   age sexe     ville date_inscription   segment
0          1     Kodjo Adjei  24.0    M   Kpalimé       2025-08-10   Nouveau
1          2     Dede Agbeko  20.0    M     Lomé        23/09/2023  Régulier
2          3  Akpene Tchassa  29.0    F   Dapaong       2025-12-11   Nouveau
3          4     Afi Tchassa  39.0    M   kpalime       2023-07-11       VIP
4          5     Sena Sossou  19.0    M  Atakpamé       07/05/2022  Régulier

In [4]:
client_id.tail()

     client_id            nom   age sexe     ville date_inscription   segment
256        257   Kodjo Agbeko  26.0    F      kara       2022-06-05   Nouveau
257        258    Essi Sossou  33.0    M   kpalime       19/02/2025       NaN
258        259    Afi Tchassa  21.0    F  Atakpamé       06/10/2022  Régulier
259        260     Sena Adjei  33.0    M      KARA       2023-11-25       VIP
260         11  Kekeli Dossou  20.0    F    Sokodé       24/07/2022  Régulier

In [5]:
client_id.shape[0] # Nombre total de lignes

261

In [6]:
client_id.info() # verification des types de donnees et valeurs manquantes

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 261 entries, 0 to 260
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   client_id         261 non-null    int64
 1   nom               261 non-null    object
 2   age               249 non-null    float64
 3   sexe              261 non-null    object
 4   ville             261 non-null    object
 5   date_inscription  261 non-null    object
 6   segment           251 non-null    object
dtypes: float64(1), int64(1), object(5)
memory usage: 14.4+ KB

In [7]:
client_id.isnull().sum()  # compteur des valeurs manquantes

client_id            0
nom                  0
age                 12
sexe                 0
ville                0
date_inscription     0
segment             10
dtype: int64

In [8]:
client_id["age"] = client_id["age"].fillna(client_id["age"].median()) #Remplacement des valeur manquantes par la mediane
client_id.isnull().sum()

client_id            0
nom                  0
age                  0
sexe                 0
ville                0
date_inscription     0
segment             10
dtype: int64

In [9]:
client_id["age"] = client_id["age"].astype(int) # Correction du type d'age DE FLOAT EN  INTEGER

In [10]:
client_id.info() #

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 261 entries, 0 to 260
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   client_id         261 non-null    int64
 1   nom               261 non-null    object
 2   age               261 non-null    int64
 3   sexe              261 non-null    object
 4   ville             261 non-null    object
 5   date_inscription  261 non-null    object
 6   segment           251 non-null    object
dtypes: int64(2), object(5)
memory usage: 14.4+ KB

-  Correction des valeur **manquantes sur la colonne segment**

In [11]:
client_id["segment"] = client_id["segment"].fillna("Inconnue") # Remplacer les valeurs manquantes par *Inconnue*

In [12]:
client_id.isnull().sum()

client_id           0
nom                 0
age                 0
sexe                0
ville               0
date_inscription    0
segment             0
dtype: int64

- Verification des ***doublons***

In [13]:
client_id.duplicated().sum()

np.int64(1)

In [87]:
client_id.drop_duplicates(inplace = True)  #Suppression des doublons

In [88]:
client_id.duplicated().sum()

np.int64(0)

- Correction des dates de la colonne ***date inscription***

In [16]:
client_id["date_inscription"] = pd.to_datetime(client_id["date_inscription"],
                                               format = "mixed",  
                                               dayfirst = True,
                                               errors = "coerce").dt.strftime("%d/%m/%Y")

In [17]:
client_id.head()  ## Correction reussi avec succes

   client_id             nom  age sexe     ville date_inscription   segment
0          1     Kodjo Adjei   24    M   Kpalimé       10/08/2025   Nouveau
1          2     Dede Agbeko   20    M     Lomé        23/09/2023  Régulier
2          3  Akpene Tchassa   29    F   Dapaong       11/12/2025   Nouveau
3          4     Afi Tchassa   39    M   kpalime       11/07/2023       VIP
4          5     Sena Sossou   19    M  Atakpamé       07/05/2022  Régulier

<h5 style = "color :red">verification des erreur d'ecrit dans les vaariables nom, age , sexe, ville, segment</h5>

- Variable ***nom***

In [18]:
client_id["nom"].unique()

array(['Kodjo Adjei', 'Dede Agbeko', 'Akpene Tchassa', 'Afi Tchassa',
       'Sena Sossou', 'Sena Kpodar', 'Kodjo Kpodar', 'Dede Bakoma',
       'Adjoa Sossou', 'Kekeli Dossou', 'Elom Agbeko', 'Essi Sossou',
       'Adjoa Adjei', 'Yao Tchassa', 'Kodjo Agbeko', 'Yao Bakoma',
       'Elom Kpodar', 'Komi Tchassa', 'Komi Kpodar', 'Kekeli Kpodar',
       'Komi Dossou', 'Afi Dossou', 'Adjoa Amouzou', 'Elom Bakoma',
       'Dede Dossou', 'Yao Kpodar', 'Yao Adjei', 'Kekeli Agbeko',
       'Elom Adjei', 'Kekeli Sossou', 'Mawuli Amouzou', 'Sena Amouzou',
       'Akpene Adjei', 'Kodjo Sossou', 'Akpene Kpodar', 'Mawuli Sossou',
       'Adjoa Kpodar', 'Dede Adjei', 'Ama Kpodar', 'Akpene Dossou',
       'Ama Tchassa', 'Dede Kpodar', 'Afi Kpodar', 'Kossi Bakoma',
       'Essi Dossou', 'Adjoa Bakoma', 'Komi Adjei', 'Kossi Dossou',
       'Komi Bakoma', 'Ama Sossou', 'Essi Amouzou', 'Dede Tchassa',
       'Ama Amouzou', 'Ama Bakoma', 'Akpene Sossou', 'Elom Dossou',
       'Dede Amouzou', 'Sena Bakoma', 'Yao Sossou', 'Fofo Tchassa',
       'Essi Agbeko', 'Kekeli Adjei', 'Afi Sossou', 'Dede Sossou',
       'Mawuli Kpodar', 'Kossi Kpodar', 'Kossi Tchassa', 'Essi Adjei',
       'Akpene Bakoma', 'Essi Kpodar', 'Adjoa Tchassa', 'Akpene Agbeko',
       'Kekeli Tchassa', 'Fofo Kpodar', 'Essi Bakoma', 'Sena Tchassa',
       'Afi Amouzou', 'Sena Adjei', 'Fofo Agbeko', 'Yao Dossou',
       'Mawuli Bakoma', 'Mawuli Tchassa', 'Elom Tchassa', 'Fofo Amouzou',
       'Akpene Amouzou', 'Kossi Agbeko', 'Komi Amouzou', 'Ama Dossou',
       'Kodjo Amouzou', 'Kossi Adjei', 'Kodjo Tchassa', 'Adjoa Dossou',
       'Kodjo Bakoma', 'Elom Amouzou', 'Komi Agbeko', 'Fofo Dossou',
       'Yao Amouzou', 'Kossi Sossou', 'Essi Tchassa', 'Komi Sossou',
       'Fofo Sossou', 'Sena Agbeko', 'Afi Bakoma', 'Kossi Amouzou',
       'Mawuli Adjei', 'Mawuli Agbeko', 'Kekeli Amouzou'], dtype=object)

***Apres analyse il y'a pas de valeur minuscule melange avec majiscule qui pourrai compromettre a  l';analyse donc la variable est sans probleme***

- Variable **sexe** :

In [19]:
client_id["sexe"].unique()

array(['M', 'F'], dtype=object)

variable sexe est sans probleme

- Variable **ville** :

In [20]:
client_id["ville"].unique()

array(['Kpalimé', 'Lomé ', 'Dapaong', 'kpalime', 'Atakpamé', 'atakpame',
       'Lomé', 'Sokodé', 'sokode', 'Kara', 'LOME', 'Sokode', 'KARA',
       'lome', 'dapaong ', ' Lomé', 'kara'], dtype=object)

In [21]:
client_id["ville"] = client_id["ville"].str.lower() #Convertir tout les villes en miniscule

In [22]:
client_id["ville"].unique()

array(['kpalimé', 'lomé ', 'dapaong', 'kpalime', 'atakpamé', 'atakpame',
       'lomé', 'sokodé', 'sokode', 'kara', 'lome', 'dapaong ', ' lomé'],
      dtype=object)

In [23]:
client_id["ville"] = client_id["ville"].astype("string").str.strip("' ")  #Supprimer les espaces entre mot et guie;llemets

In [59]:
client_id["ville"].unique()

<StringArray>
[ 'kpalimé',     'lomé',  'dapaong',  'kpalime', 'atakpamé', 'atakpame',
   'sokodé',   'sokode',     'kara',     'lome']
Length: 10, dtype: string

In [62]:
client_id["ville"]  = client_id["ville"].replace({ # Rempolacerment des nom des pays par les nom correctes
    "kpalime"   : "Kpalimé",
    "atakpame"  : "Atakpamé",
    "sokode"    : "Sokodé",
    "lome"      : "Lomé",
    "kara"      : "Kara",
    "dapaong"   : "Dapaong",
    "lomé"      :  "Lomé",
    "kpalimé"   :  "Kpalimé",
    "atakpamé"  :  "Atakpamé",
    "sokodé"    :  "Sokodé"
})

In [63]:
client_id["ville"].unique()

<StringArray>
['Kpalimé', 'Lomé', 'Dapaong', 'Atakpamé', 'Sokodé', 'Kara']
Length: 6, dtype: string

- Variable segment

In [26]:
client_id["segment"].unique()

array(['Nouveau', 'Régulier', 'VIP', 'Inconnue'], dtype=object)

### 2-)Analyse du fichier contenant les produits de l'entreprise

In [27]:
produit.head()

,product_id,category,brand,cost_price,list_price,stock_quantity,supplier_id
0,1,Cyclisme,Vela,41.0,95.5,333,2
1,2,Running,Kaito,40.1,56.3,199,5
2,3,Running,Atlas,24.2,42.8,136,2
3,4,Yoga,Kaito,23.4,46.8,233,4
4,5,Basketball,Prime,36.9,79.2,136,6

In [28]:
produit.tail()

,product_id,category,brand,cost_price,list_price,stock_quantity,supplier_id
86,87,Yoga,Nova,44.8,NaN,101,6
87,88,Basketball,Kaito,21.4,35.7,205,1
88,89,Football,Nova,25.6,39.7,67,2
89,90,Basketball,Prime,24.9,40.3,65,5
90,4,Yoga,Kaito,23.4,46.8,238,4

In [29]:
produit.shape[0] # Nombre de licgne de ce dataset

91

In [30]:
produit.head()

,product_id,category,brand,cost_price,list_price,stock_quantity,supplier_id
0,1,Cyclisme,Vela,41.0,95.5,333,2
1,2,Running,Kaito,40.1,56.3,199,5
2,3,Running,Atlas,24.2,42.8,136,2
3,4,Yoga,Kaito,23.4,46.8,233,4
4,5,Basketball,Prime,36.9,79.2,136,6

In [31]:
produit.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 91 entries, 0 to 90
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   product_id      91 non-null     int64
 1   category        91 non-null     object
 2   brand           91 non-null     object
 3   cost_price      91 non-null     float64
 4   list_price      86 non-null     float64
 5   stock_quantity  91 non-null     int64
 6   supplier_id     91 non-null     int64
dtypes: float64(2), int64(3), object(2)
memory usage: 5.1+ KB

- Correction des valeurs manquantes

In [32]:
produit.isnull().sum()

product_id        0
category          0
brand             0
cost_price        0
list_price        5
stock_quantity    0
supplier_id       0
dtype: int64

catalogue_produit.dropna(inplace = True)  # j'ai supprimer toutes les lignes contenant des prix de ventes 
                                        # manquantes par ce que pour moi cela n'agit pas de trop sur no article

In [33]:
produit.isnull().sum()

product_id        0
category          0
brand             0
cost_price        0
list_price        5
stock_quantity    0
supplier_id       0
dtype: int64

- Verification des doublons

In [34]:
produit.duplicated().sum()  # Zero doublon dans ce dataset

np.int64(0)

<h5 style = "color : red">Verification des  erreur d'ecriture dans les variables categorie_sport et marque</h5>

- Variable **categorie_sport**

In [35]:
produit["category"].unique()

array(['Cyclisme', 'Running', 'Yoga', 'Basketball', 'Football',
       'football ', 'BASKETBALL', 'Fitness', 'FOOTBALL', 'running ',
       'fitness ', 'yoga ', 'basketball ', 'CYCLISME', 'cyclisme '],
      dtype=object)

- On remarque qu'il y'a des nom comme Cyclisme, CYCLISME, cyclisme pour l'etre humains on considere cela que 
c'est la meme chose mais pandas lui va penser qu'il sont diff donc corrrigosn cela

In [36]:
produit["category"] = produit["category"].astype("string").str.strip("'")

In [37]:
produit["category"].unique()

<StringArray>
[   'Cyclisme',     'Running',        'Yoga',  'Basketball',    'Football',
   'football ',  'BASKETBALL',     'Fitness',    'FOOTBALL',    'running ',
    'fitness ',       'yoga ', 'basketball ',    'CYCLISME',   'cyclisme ']
Length: 15, dtype: string

In [38]:
produit["category"] = produit["category"].str.lower()

In [39]:
produit["category"].unique()

<StringArray>
[   'cyclisme',     'running',        'yoga',  'basketball',    'football',
   'football ',     'fitness',    'running ',    'fitness ',       'yoga ',
 'basketball ',   'cyclisme ']
Length: 12, dtype: string

- <p style = "color : red">Changement des noms des variables de notre dataframe contenant les produits</p>

In [40]:
produit.rename({
    "product_id"      : "id_produit",
     "category"       : "categorie",
     "brand"          : "marque",
     "cost_price"     : "prix_achat",
     "list_price"     : "prix_vente",
     "stock_quantity" : "stock_dispo",
     "supplier_id"    : "ref_fournisseur"
}, axis = 1, inplace = True)

In [41]:
produit.head()

,id_produit,categorie,marque,prix_achat,prix_vente,stock_dispo,ref_fournisseur
0,1,cyclisme,Vela,41.0,95.5,333,2
1,2,running,Kaito,40.1,56.3,199,5
2,3,running,Atlas,24.2,42.8,136,2
3,4,yoga,Kaito,23.4,46.8,233,4
4,5,basketball,Prime,36.9,79.2,136,6

### 3-) Analyse et netoyage du fichier commande_pass

In [42]:
commande_pass.head()

,order_id,date,client_id,product_id,quantity,discount_pct,payment_method,region,delivery_time_days,status
0,1,02/01/2025,70,31,2,0,Paiement à la livraison,Kpalimé,3.2,Livrée
1,2,2025-01-02,218,85,1,15,carte,Kara,4.3,Livrée
2,3,2025-01-02,158,62,1,0,Mobile Money,Lomé,2.2,Livrée
3,4,2025-01-03,205,76,1,0,Mobile_Money,Kara,6.1,Livrée
4,5,2025-01-03,250,47,2,15,Mobile Money,Sokodé,3.8,Livrée

- <p style = "color : red">changement des noms de nos variables</p>

In [43]:
commande_pass.rename({
       "order_id"           :  "id_unique",
       "date"               :  "date_commande",
       "client_id"          :  "id_client",
       "product_id"         :  "id_produit",
       "quantity"           :  "quantite",
       "discount_pct"       :  "reduction(%)",
       "payment_method"     :  "mode_payement",
       "region"             :  "region",
       "delivery_time_days" :  "delai_livraison",
}, axis = 1, inplace  = True)

In [44]:
commande_pass.head() 
# Pour les lignes dont livraison est vide == > livraison en cours

,id_unique,date_commande,id_client,id_produit,quantite,reduction(%),mode_payement,region,delai_livraison,status
0,1,02/01/2025,70,31,2,0,Paiement à la livraison,Kpalimé,3.2,Livrée
1,2,2025-01-02,218,85,1,15,carte,Kara,4.3,Livrée
2,3,2025-01-02,158,62,1,0,Mobile Money,Lomé,2.2,Livrée
3,4,2025-01-03,205,76,1,0,Mobile_Money,Kara,6.1,Livrée
4,5,2025-01-03,250,47,2,15,Mobile Money,Sokodé,3.8,Livrée

In [45]:
commande_pass.shape[0]  # Nomcbre de ligne

1237

In [46]:
commande_pass.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1237 entries, 0 to 1236
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id_unique        1237 non-null   int64
 1   date_commande    1237 non-null   object
 2   id_client        1237 non-null   int64
 3   id_produit       1237 non-null   int64
 4   quantite         1237 non-null   int64
 5   reduction(%)     1237 non-null   int64
 6   mode_payement    1237 non-null   object
 7   region           1237 non-null   object
 8   delai_livraison  1126 non-null   float64
 9   status           1237 non-null   object
dtypes: float64(1), int64(5), object(4)
memory usage: 96.8+ KB

In [47]:
commande_pass.isnull().sum()  #Pour les delai de livraison  , les valeur manquante  ==> indique que la commande est en cours

id_unique            0
date_commande        0
id_client            0
id_produit           0
quantite             0
reduction(%)         0
mode_payement        0
region               0
delai_livraison    111
status               0
dtype: int64

- <p style = "color :red">Correction des erreur dans les dates</p>

In [48]:
commande_pass["date_commande"].unique()    # Il y'a des erreur , donc je dois modifier

array(['02/01/2025', '2025-01-02', '2025-01-03', '03/01/2025',
       '2025-01-04', '2025-01-05', '2025-01-06', '2025-01-07',
       '2025-01-08', '2025-01-09', '09/01/2025', '2025-01-10',
       '11/01/2025', '2025-01-11', '2025-01-12', '2025-01-13',
       '13/01/2025', '2025-01-14', '2025-01-15', '2025-01-16',
       '2025-01-17', '2025-01-18', '2025-01-19', '2025-01-20',
       '20/01/2025', '2025-01-21', '2025-01-22', '22/01/2025',
       '2025-01-23', '2025-01-24', '2025-01-25', '25/01/2025',
       '2025-01-27', '2025-01-28', '2025-01-29', '2025-01-30',
       '2025-01-31', '01/02/2025', '2025-02-02', '2025-02-03',
       '2025-02-04', '2025-02-05', '05/02/2025', '2025-02-06',
       '2025-02-07', '2025-02-08', '2025-02-09', '10/02/2025',
       '2025-02-10', '2025-02-12', '12/02/2025', '2025-02-13',
       '13/02/2025', '2025-02-14', '2025-02-15', '16/02/2025',
       '2025-02-16', '2025-02-17', '2025-02-18', '2025-02-19',
       '2025-02-20', '2025-02-21', '2025-02-22', '22/02/2025',
       '2025-02-23', '23/02/2025', '2025-02-24', '25/02/2025',
       '2025-02-25', '2025-02-26', '2025-02-27', '2025-02-28',
       '2025-03-01', '01/03/2025', '02/03/2025', '2025-03-02',
       '2025-03-03', '2025-03-04', '2025-03-05', '05/03/2025',
       '2025-03-06', '06/03/2025', '2025-03-07', '2025-03-08',
       '2025-03-09', '2025-03-10', '2025-03-11', '2025-03-12',
       '12/03/2025', '2025-03-13', '2025-03-14', '2025-03-15',
       '15/03/2025', '2025-03-16', '17/03/2025', '18/03/2025',
       '2025-03-18', '2025-03-19', '2025-03-20', '2025-03-21',
       '2025-03-22', '2025-03-23', '2025-03-24', '24/03/2025',
       '25/03/2025', '2025-03-25', '2025-03-26', '2025-03-27',
       '2025-03-28', '2025-03-29', '29/03/2025', '2025-03-30',
       '30/03/2025', '2025-03-31', '01/04/2025', '2025-04-01',
       '2025-04-02', '2025-04-03', '2025-04-04', '2025-04-05',
       '2025-04-06', '06/04/2025', '2025-04-07', '07/04/2025',
       '2025-04-08', '08/04/2025', '2025-04-09', '09/04/2025',
       '2025-04-10', '10/04/2025', '2025-04-11', '12/04/2025',
       '2025-04-12', '2025-04-13', '2025-04-14', '2025-04-15',
       '15/04/2025', '2025-04-16', '16/04/2025', '2025-04-17',
       '2025-04-18', '2025-04-19', '2025-04-20', '21/04/2025',
       '2025-04-21', '2025-04-22', '2025-04-23', '2025-04-24',
       '24/04/2025', '2025-04-25', '25/04/2025', '2025-04-26',
       '2025-04-27', '27/04/2025', '2025-04-28', '28/04/2025',
       '29/04/2025', '2025-04-29', '2025-05-01', '2025-05-02',
       '2025-05-03', '2025-05-04', '04/05/2025', '2025-05-05',
       '2025-05-06', '06/05/2025', '2025-05-07', '07/05/2025',
       '08/05/2025', '2025-05-08', '2025-05-09', '09/05/2025',
       '2025-05-10', '11/05/2025', '2025-05-12', '2025-05-13',
       '2025-05-14', '14/05/2025', '2025-05-15', '2025-05-16',
       '2025-05-17', '2025-05-18', '2025-05-19', '2025-05-20',
       '21/05/2025', '2025-05-21', '2025-05-22', '2025-05-23',
       '24/05/2025', '2025-05-24', '2025-05-25', '2025-05-26',
       '26/05/2025', '2025-05-27', '2025-05-28', '2025-05-29',
       '2025-05-30', '31/05/2025', '2025-06-01', '01/06/2025',
       '2025-06-02', '2025-06-03', '2025-06-04', '2025-06-05',
       '05/06/2025', '06/06/2025', '2025-06-06', '2025-06-07',
       '08/06/2025', '2025-06-08', '2025-06-09', '2025-06-10',
       '2025-06-11', '11/06/2025', '2025-06-12', '2025-06-13',
       '2025-06-14', '14/06/2025', '2025-06-15', '2025-06-16',
       '17/06/2025', '2025-06-17', '2025-06-18', '2025-06-19',
       '2025-06-20', '2025-06-22', '22/06/2025', '23/06/2025',
       '2025-06-24', '2025-06-25', '2025-06-26', '2025-06-27',
       '27/06/2025', '2025-06-28', '29/06/2025', '2025-06-29',
       '2025-06-30', '2025-07-01', '2025-07-02', '2025-07-04',
       '2025-07-05', '2025-07-07', '2025-07-08', '2025-07-09',
       '2025-07-10', '2025-07-11', '2025-07-13', '13/07/2025',
       '2025-07-14', '14/07/2025', '2025-07-16', '2025-07-18',
       '2025-07-19', '20/07/2025', '2025-07-20', '2025-07-21',
       '22/07/2025', '2025-07-22', '2025-07-23', '2025-07-24',
       '25/07/2025', '26/07/2025', '2025-07-26', '2025-07-29',
       '2025-07-31', '2025-08-02', '2025-08-03', '04/08/2025',
       '2025-08-05', '2025-08-08', '2025-08-09', '2025-08-10',
       '10/08/2025', '2025-08-11', '12/08/2025', '2025-08-12',
       '2025-08-13', '2025-08-14', '2025-08-15', '2025-08-16',
       '2025-08-18', '2025-08-19', '2025-08-20', '2025-08-21',
       '2025-08-22', '2025-08-24', '2025-08-25', '25/08/2025',
       '2025-08-27', '27/08/2025', '2025-08-28', '2025-08-29',
       '29/08/2025', '2025-08-30', '2025-08-31', '2025-09-01',
       '2025-09-02', '2025-09-03', '2025-09-04', '04/09/2025',
       '2025-09-05', '05/09/2025', '2025-09-06', '06/09/2025',
       '2025-09-07', '2025-09-08', '09/09/2025', '2025-09-09',
       '2025-09-11', '11/09/2025', '2025-09-13', '13/09/2025',
       '2025-09-14', '2025-09-15', '15/09/2025', '2025-09-16',
       '16/09/2025', '17/09/2025', '2025-09-17', '2025-09-18',
       '2025-09-19', '19/09/2025', '2025-09-20', '2025-09-21',
       '21/09/2025', '2025-09-22', '23/09/2025', '25/09/2025',
       '2025-09-25', '2025-09-26', '26/09/2025', '2025-09-27',
       '2025-09-28', '2025-09-29', '2025-09-30', '30/09/2025',
       '2025-10-01', '01/10/2025', '2025-10-02', '2025-10-03',
       '2025-10-04', '04/10/2025', '2025-10-05', '05/10/2025',
       '2025-10-06', '06/10/2025', '2025-10-07', '2025-10-08',
       '2025-10-09', '09/10/2025', '2025-10-10', '2025-10-11',
       '2025-10-12', '12/10/2025', '2025-10-13', '2025-10-14',
       '14/10/2025', '2025-10-15', '2025-10-16', '17/10/2025',
       '2025-10-17', '2025-10-18', '19/10/2025', '2025-10-19',
       '2025-10-20', '2025-10-21', '21/10/2025', '2025-10-22',
       '23/10/2025', '2025-10-23', '2025-10-24', '24/10/2025',
       '25/10/2025', '2025-10-25', '2025-10-26', '27/10/2025',
       '2025-10-27', '2025-10-28', '2025-10-30', '31/10/2025',
       '2025-10-31', '2025-11-01', '2025-11-02', '02/11/2025',
       '2025-11-03', '03/11/2025', '2025-11-04', '04/11/2025',
       '2025-11-05', '2025-11-06', '2025-11-07', '08/11/2025',
       '2025-11-08', '2025-11-09', '2025-11-10', '10/11/2025',
       '2025-11-11', '2025-11-12', '12/11/2025', '2025-11-13',
       '14/11/2025', '2025-11-14', '2025-11-15', '15/11/2025',
       '2025-11-16', '16/11/2025', '2025-11-17', '2025-11-18',
       '18/11/2025', '2025-11-19', '19/11/2025', '2025-11-20',
       '2025-11-21', '2025-11-22', '22/11/2025', '2025-11-23',
       '23/11/2025', '24/11/2025', '2025-11-24', '25/11/2025',
       '2025-11-25', '2025-11-26', '2025-11-27', '2025-11-28',
       '2025-11-29', '2025-11-30', '30/11/2025', '2025-12-01',
       '2025-12-02', '2025-12-03', '2025-12-04', '2025-12-05',
       '2025-12-06', '2025-12-07', '2025-12-08', '2025-12-09',
       '09/12/2025', '2025-12-10', '10/12/2025', '2025-12-11',
       '11/12/2025', '2025-12-12', '13/12/2025', '2025-12-13',
       '14/12/2025', '2025-12-14', '15/12/2025', '2025-12-15',
       '2025-12-16', '2025-12-17', '2025-12-18', '2025-12-19',
       '2025-12-20', '20/12/2025', '2025-12-21', '2025-12-22',
       '2025-12-23', '23/12/2025', '2025-12-24', '24/12/2025',
       '2025-12-25', '25/12/2025', '2025-12-26', '26/12/2025',
       '2025-12-27', '2025-12-28', '2025-12-29', '29/12/2025',
       '2025-12-30', '2025-12-31'], dtype=object)

In [49]:
commande_pass["date_commande"] = pd.to_datetime(commande_pass["date_commande"], 
                                                format = "mixed",
                                                dayfirst = True,
                                                errors = "coerce"
                                               ).dt.strftime("%d/%m/%Y")

In [50]:
commande_pass["date_commande"].unique() # Correction , en faite j'ai reconvertie en format francais

array(['02/01/2025', '03/01/2025', '04/01/2025', '05/01/2025',
       '06/01/2025', '07/01/2025', '08/01/2025', '09/01/2025',
       '10/01/2025', '11/01/2025', '12/01/2025', '13/01/2025',
       '14/01/2025', '15/01/2025', '16/01/2025', '17/01/2025',
       '18/01/2025', '19/01/2025', '20/01/2025', '21/01/2025',
       '22/01/2025', '23/01/2025', '24/01/2025', '25/01/2025',
       '27/01/2025', '28/01/2025', '29/01/2025', '30/01/2025',
       '31/01/2025', '01/02/2025', '02/02/2025', '03/02/2025',
       '04/02/2025', '05/02/2025', '06/02/2025', '07/02/2025',
       '08/02/2025', '09/02/2025', '10/02/2025', '12/02/2025',
       '13/02/2025', '14/02/2025', '15/02/2025', '16/02/2025',
       '17/02/2025', '18/02/2025', '19/02/2025', '20/02/2025',
       '21/02/2025', '22/02/2025', '23/02/2025', '24/02/2025',
       '25/02/2025', '26/02/2025', '27/02/2025', '28/02/2025',
       '01/03/2025', '02/03/2025', '03/03/2025', '04/03/2025',
       '05/03/2025', '06/03/2025', '07/03/2025', '08/03/2025',
       '09/03/2025', '10/03/2025', '11/03/2025', '12/03/2025',
       '13/03/2025', '14/03/2025', '15/03/2025', '16/03/2025',
       '17/03/2025', '18/03/2025', '19/03/2025', '20/03/2025',
       '21/03/2025', '22/03/2025', '23/03/2025', '24/03/2025',
       '25/03/2025', '26/03/2025', '27/03/2025', '28/03/2025',
       '29/03/2025', '30/03/2025', '31/03/2025', '01/04/2025',
       '02/04/2025', '03/04/2025', '04/04/2025', '05/04/2025',
       '06/04/2025', '07/04/2025', '08/04/2025', '09/04/2025',
       '10/04/2025', '11/04/2025', '12/04/2025', '13/04/2025',
       '14/04/2025', '15/04/2025', '16/04/2025', '17/04/2025',
       '18/04/2025', '19/04/2025', '20/04/2025', '21/04/2025',
       '22/04/2025', '23/04/2025', '24/04/2025', '25/04/2025',
       '26/04/2025', '27/04/2025', '28/04/2025', '29/04/2025',
       '01/05/2025', '02/05/2025', '03/05/2025', '04/05/2025',
       '05/05/2025', '06/05/2025', '07/05/2025', '08/05/2025',
       '09/05/2025', '10/05/2025', '11/05/2025', '12/05/2025',
       '13/05/2025', '14/05/2025', '15/05/2025', '16/05/2025',
       '17/05/2025', '18/05/2025', '19/05/2025', '20/05/2025',
       '21/05/2025', '22/05/2025', '23/05/2025', '24/05/2025',
       '25/05/2025', '26/05/2025', '27/05/2025', '28/05/2025',
       '29/05/2025', '30/05/2025', '31/05/2025', '01/06/2025',
       '02/06/2025', '03/06/2025', '04/06/2025', '05/06/2025',
       '06/06/2025', '07/06/2025', '08/06/2025', '09/06/2025',
       '10/06/2025', '11/06/2025', '12/06/2025', '13/06/2025',
       '14/06/2025', '15/06/2025', '16/06/2025', '17/06/2025',
       '18/06/2025', '19/06/2025', '20/06/2025', '22/06/2025',
       '23/06/2025', '24/06/2025', '25/06/2025', '26/06/2025',
       '27/06/2025', '28/06/2025', '29/06/2025', '30/06/2025',
       '01/07/2025', '02/07/2025', '04/07/2025', '05/07/2025',
       '07/07/2025', '08/07/2025', '09/07/2025', '10/07/2025',
       '11/07/2025', '13/07/2025', '14/07/2025', '16/07/2025',
       '18/07/2025', '19/07/2025', '20/07/2025', '21/07/2025',
       '22/07/2025', '23/07/2025', '24/07/2025', '25/07/2025',
       '26/07/2025', '29/07/2025', '31/07/2025', '02/08/2025',
       '03/08/2025', '04/08/2025', '05/08/2025', '08/08/2025',
       '09/08/2025', '10/08/2025', '11/08/2025', '12/08/2025',
       '13/08/2025', '14/08/2025', '15/08/2025', '16/08/2025',
       '18/08/2025', '19/08/2025', '20/08/2025', '21/08/2025',
       '22/08/2025', '24/08/2025', '25/08/2025', '27/08/2025',
       '28/08/2025', '29/08/2025', '30/08/2025', '31/08/2025',
       '01/09/2025', '02/09/2025', '03/09/2025', '04/09/2025',
       '05/09/2025', '06/09/2025', '07/09/2025', '08/09/2025',
       '09/09/2025', '11/09/2025', '13/09/2025', '14/09/2025',
       '15/09/2025', '16/09/2025', '17/09/2025', '18/09/2025',
       '19/09/2025', '20/09/2025', '21/09/2025', '22/09/2025',
       '23/09/2025', '25/09/2025', '26/09/2025', '27/09/2025',
       '28/09/2025', '29/09/2025', '30/09/2025', '01/10/2025',
       '02/10/2025', '03/10/2025', '04/10/2025', '05/10/2025',
       '06/10/2025', '07/10/2025', '08/10/2025', '09/10/2025',
       '10/10/2025', '11/10/2025', '12/10/2025', '13/10/2025',
       '14/10/2025', '15/10/2025', '16/10/2025', '17/10/2025',
       '18/10/2025', '19/10/2025', '20/10/2025', '21/10/2025',
       '22/10/2025', '23/10/2025', '24/10/2025', '25/10/2025',
       '26/10/2025', '27/10/2025', '28/10/2025', '30/10/2025',
       '31/10/2025', '01/11/2025', '02/11/2025', '03/11/2025',
       '04/11/2025', '05/11/2025', '06/11/2025', '07/11/2025',
       '08/11/2025', '09/11/2025', '10/11/2025', '11/11/2025',
       '12/11/2025', '13/11/2025', '14/11/2025', '15/11/2025',
       '16/11/2025', '17/11/2025', '18/11/2025', '19/11/2025',
       '20/11/2025', '21/11/2025', '22/11/2025', '23/11/2025',
       '24/11/2025', '25/11/2025', '26/11/2025', '27/11/2025',
       '28/11/2025', '29/11/2025', '30/11/2025', '01/12/2025',
       '02/12/2025', '03/12/2025', '04/12/2025', '05/12/2025',
       '06/12/2025', '07/12/2025', '08/12/2025', '09/12/2025',
       '10/12/2025', '11/12/2025', '12/12/2025', '13/12/2025',
       '14/12/2025', '15/12/2025', '16/12/2025', '17/12/2025',
       '18/12/2025', '19/12/2025', '20/12/2025', '21/12/2025',
       '22/12/2025', '23/12/2025', '24/12/2025', '25/12/2025',
       '26/12/2025', '27/12/2025', '28/12/2025', '29/12/2025',
       '30/12/2025', '31/12/2025'], dtype=object)

---

  <p style = "color : red">Verification des erreur de saisie</p>

- Dans la variable  ***mode_payement***

In [51]:
commande_pass.head()

,id_unique,date_commande,id_client,id_produit,quantite,reduction(%),mode_payement,region,delai_livraison,status
0,1,02/01/2025,70,31,2,0,Paiement à la livraison,Kpalimé,3.2,Livrée
1,2,02/01/2025,218,85,1,15,carte,Kara,4.3,Livrée
2,3,02/01/2025,158,62,1,0,Mobile Money,Lomé,2.2,Livrée
3,4,03/01/2025,205,76,1,0,Mobile_Money,Kara,6.1,Livrée
4,5,03/01/2025,250,47,2,15,Mobile Money,Sokodé,3.8,Livrée

In [52]:
commande_pass["mode_payement"].unique()

array(['Paiement à la livraison', 'carte', 'Mobile Money', 'Mobile_Money',
       'MOMO', 'Carte bancaire', 'cash', 'mobile money', 'CB',
       'Cash a la livraison'], dtype=object)

In [53]:
# Les modes de payment que moi je vois la me semble trop bizzarre, mais sais que ceux ci sont des modes de payement  :
#  - Par Carte banquaire
#  - cash (Paieyemment a a la livraison)
#  - mobile_money
# Le reste je ne connais pas donc je vais les remplacer:

# Deja je peut dire que ce son des erreur de saisie car:
# MOMO == >Mobile Money , certains qiue cette personne voulais ecrire Mobile Money mais a voulu abreger

In [54]:
commande_pass["mode_payement"] = commande_pass["mode_payement"].str.lower() # Convertion des nom en minuscule

In [55]:
commande_pass["mode_payement"].unique()

array(['paiement à la livraison', 'carte', 'mobile money', 'mobile_money',
       'momo', 'carte bancaire', 'cash', 'cb', 'cash a la livraison'],
      dtype=object)

In [56]:
commande_pass["mode_payement"] = commande_pass["mode_payement"].replace({
    "momo"                    :     "mobile_money",
    "cash a la livraison"     :     "paiement à la livraison",
    "carte"                   :    "carte_bancaire",
    "cash"                    :    "paiement à la livraison",
    "cb"                     :    "carte_bancaire",
    "mobile money"            :    "mobile_money"
})

In [64]:
commande_pass["mode_payement"].unique() # Correctgion effectue avec succes

array(['paiement à la livraison', 'carte_bancaire', 'mobile_money',
       'carte bancaire'], dtype=object)

- Dans la variable  ***region***

In [66]:
commande_pass["region"].unique() #On trouve auccun problenm dde saisie dans cette variable

array(['Kpalimé', 'Kara', 'Lomé', 'Sokodé', 'Atakpamé', 'Dapaong'],
      dtype=object)

- Dans la variable  ***status***

In [68]:
commande_pass["status"].unique() #Aucun probcleme

array(['Livrée', 'En cours', 'Annulée', 'Retournée'], dtype=object)

---

- <p style = "color : red ">Verification et correction des doublon de notre dataset commande_pass</p>

In [82]:
commande_pass.duplicated().sum()  # verification des docublon

np.int64(0)

In [83]:
commande_pass.drop_duplicates(inplace = True)

In [84]:
commande_pass.duplicated().sum()

np.int64(0)

In [94]:
commande_pass[commande_pass["quantite"]<0]

,id_unique,date_commande,id_client,id_produit,quantite,reduction(%),mode_payement,region,delai_livraison,status
43,44,17/01/2025,233,39,-1,10,mobile_money,Atakpamé,4.6,Livrée
57,58,22/01/2025,241,20,-1,0,mobile_money,Dapaong,4.9,Livrée
649,650,16/07/2025,133,64,-1,0,mobile_money,Kara,1.9,Annulée
664,665,23/07/2025,221,88,-1,20,carte_bancaire,Lomé,1.0,Retournée

### 4 -Analyse et netoyage du fichier fournisseurs

In [69]:
fournisseurs.head()

,supplier_id,supplier_name,country,lead_time_days,reliability_score
0,1,AfricaSport Import,Togo,3,4.6
1,2,GlobalGear Ltd,Chine,21,4.1
2,3,EuroFit Distribution,France,12,4.7
3,4,SahelTex,Côte d'Ivoire,6,3.9
4,5,Prime Athletics,Chine,25,NaN

- <p style = "color : red">Changement des noms des variable(nenommer)</p>

In [71]:
fournisseurs.rename({
    "supplier_id"       :      "id_unique",
    "supplier_name"     :      "nom_fournisseur",
    "country"           :      "pays",
    "lead_time_days"    :      "delai_approvision(jours)",
    "reliability_score" :      "score_fiabilte"
}, axis = 1, inplace = True)

In [74]:
fournisseurs

,id_unique,nom_fournisseur,pays,delai_approvision(jours),score_fiabilte
0,1,AfricaSport Import,Togo,3,4.6
1,2,GlobalGear Ltd,Chine,21,4.1
2,3,EuroFit Distribution,France,12,4.7
3,4,SahelTex,Côte d'Ivoire,6,3.9
4,5,Prime Athletics,Chine,25,NaN
5,6,Naija Sports Supply,Nigeria,8,4.0

Le fournisseur de ***la chine*** n'a pas donner son score, Sinon ce dataset est deja propres

### 5 - Analyse et netoyage du fichier avis_clients

In [89]:
avis_clients.head()

   review_id  order_id  rating  comment_length
0          1       813     5.0              16
1          2        56     4.0             128
2          3      1145     3.0              93
3          4       683     4.0              77
4          5       312     4.0              61

- <p style = "color : red">Modification des nom des variable(renommer)</p>

In [90]:
avis_clients.rename({
    "review_id"       :        "id_unique",
     "order_id"       :        "ref_commande",
     "rating"         :        "note_laissee",
     "comment_length" :        "longueur_comment"
}, axis = 1, inplace = True)

In [91]:
avis_clients.head()

   id_unique  ref_commande  note_laissee  longueur_comment
0          1           813           5.0                16
1          2            56           4.0               128
2          3          1145           3.0                93
3          4           683           4.0                77
4          5           312           4.0                61