In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("clients_assurance.csv")
df

,id_client,nom,age,type_contrat,date_contrat,region,prime,nb_sinistres,montant_sinistres
0,100,Client_100,35.0,auto,2022-04-23,Savanes,324.63,3,810.05
1,298,Client_298,57.0,MOTO,2020-04-05,Plateaux,172.37,0,0.00
2,90,Client_90,65.0,habitation,2020-08-03,Plateaux,179.38,1,612.00
3,31,Client_31,NaN,auto,2021-02-05,Savanes,245.67,0,0.00
4,236,Client_236,69.0,habitation,2021-12-23,Maritime,130.21,1,567.57
...,...,...,...,...,...,...,...,...,...
300,300,Client_300,35.0,habitation,2023-01-06,Savanes,246.54,0,0.00
301,23,Client_23,61.0,sante,2020-03-18,Plateaux,161.38,0,0.00
302,73,Client_73,57.0,auto,2022-10-17,Savanes,249.28,0,0.00
303,16,Client_16,57.0,auto,2022-03-08,Plateaux,343.54,0,0.00
304,169,Client_169,NaN,sante,2021-01-05,Maritime,60.17,0,0.00

In [3]:
df.info()    ##AMALYSE DES TYPES DE DONNES DU DATASET

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 305 entries, 0 to 304
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id_client          305 non-null    int64
 1   nom                305 non-null    object
 2   age                293 non-null    float64
 3   type_contrat       305 non-null    object
 4   date_contrat       305 non-null    object
 5   region             299 non-null    object
 6   prime              296 non-null    float64
 7   nb_sinistres       305 non-null    int64
 8   montant_sinistres  305 non-null    float64
dtypes: float64(3), int64(2), object(4)
memory usage: 21.6+ KB

In [4]:
df.isnull()  ##verifvions voir s'il y'a des element manquant dans le dataset

,id_client,nom,age,type_contrat,date_contrat,region,prime,nb_sinistres,montant_sinistres
0,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False
3,False,False,True,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...
300,False,False,False,False,False,False,False,False,False
301,False,False,False,False,False,False,False,False,False
302,False,False,False,False,False,False,False,False,False
303,False,False,False,False,False,False,False,False,False
304,False,False,True,False,False,False,False,False,False

In [5]:
vl = df.loc[20 : 50]
vl   Analyse entre

,id_client,nom,age,type_contrat,date_contrat,region,prime,nb_sinistres,montant_sinistres
20,113,Client_113,24.0,auto,2023-07-01,Kara,453.19,2,1474.88
21,160,Client_160,56.0,auto,2023-11-29,Kara,322.86,0,0.00
22,241,Client_241,66.0,auto,2023-08-21,Centrale,286.25,0,0.00
23,198,Client_198,61.0,AUTO,2023-04-17,Kara,296.21,0,0.00
24,255,Client_255,18.0,sante,2021-05-16,Kara,365.06,1,312.35
25,30,Client_30,39.0,moto,2020-03-29,Maritime,192.28,0,0.00
26,143,Client_143,52.0,auto,2023-02-03,Centrale,318.40,0,0.00
27,170,Client_170,56.0,auto,2022-07-24,Kara,264.87,0,0.00
28,222,Client_222,50.0,auto,2020-12-07,Kara,376.43,1,1117.82
29,4,Client_4,32.0,auto,2021-08-10,Maritime,257.70,0,0.00
30,161,Client_161,44.0,auto,2023-10-01,Savanes,400.07,1,416.95
31,141,Client_141,41.0,auto,2022-06-06,Centrale,326.69,0,0.00
32,254,Client_254,50.0,sante,2020-07-12,Maritime,130.73,0,0.00
33,259,Client_259,61.0,auto,2023-05-30,Savanes,365.52,0,0.00
34,293,Client_293,49.0,moto,2024-06-20,NaN,218.07,0,0.00
35,286,Client_286,37.0,auto,2020-11-23,Kara,NaN,0,0.00
36,134,Client_134,25.0,auto,2021-11-13,Kara,273.42,0,0.00
37,215,Client_215,20.0,auto,2022-08-24,Plateaux,427.78,2,2617.09
38,276,Client_276,39.0,auto,2024-12-28,Centrale,318.76,0,0.00
39,250,Client_250,71.0,habitation,2021-08-12,Centrale,218.83,0,0.00
40,54,Client_54,42.0,habitation,2024-07-27,Savanes,130.18,1,1368.57
41,183,Client_183,53.0,habitation,2020-08-31,Maritime,224.60,0,0.00
42,231,Client_231,41.0,sante,2023-03-10,Kara,177.13,0,0.00
43,185,Client_185,49.0,sante,2024-06-13,Savanes,194.15,0,0.00
44,75,Client_75,19.0,auto,2023-12-05,Savanes,516.20,1,256.86
45,189,Client_189,45.0,habitation,2021-04-19,Kara,134.87,0,0.00
46,176,Client_176,54.0,habitation,2020-07-20,Maritime,159.19,0,0.00
47,127,Client_127,22.0,auto,2022-08-15,Kara,432.49,1,1345.89
48,67,Client_67,64.0,moto,2022-07-11,Plateaux,100.72,1,362.80
49,42,Client_42,72.0,HABITATION,2020-05-22,Maritime,122.83,0,0.00
50,12,Client_12,28.0,moto,2024-12-07,Plateaux,160.48,0,0.00

In [6]:
vl.isnull() ## Recherche de valeur manqant

,id_client,nom,age,type_contrat,date_contrat,region,prime,nb_sinistres,montant_sinistres
20,False,False,False,False,False,False,False,False,False
21,False,False,False,False,False,False,False,False,False
22,False,False,False,False,False,False,False,False,False
23,False,False,False,False,False,False,False,False,False
24,False,False,False,False,False,False,False,False,False
25,False,False,False,False,False,False,False,False,False
26,False,False,False,False,False,False,False,False,False
27,False,False,False,False,False,False,False,False,False
28,False,False,False,False,False,False,False,False,False
29,False,False,False,False,False,False,False,False,False
30,False,False,False,False,False,False,False,False,False
31,False,False,False,False,False,False,False,False,False
32,False,False,False,False,False,False,False,False,False
33,False,False,False,False,False,False,False,False,False
34,False,False,False,False,False,True,False,False,False
35,False,False,False,False,False,False,True,False,False
36,False,False,False,False,False,False,False,False,False
37,False,False,False,False,False,False,False,False,False
38,False,False,False,False,False,False,False,False,False
39,False,False,False,False,False,False,False,False,False
40,False,False,False,False,False,False,False,False,False
41,False,False,False,False,False,False,False,False,False
42,False,False,False,False,False,False,False,False,False
43,False,False,False,False,False,False,False,False,False
44,False,False,False,False,False,False,False,False,False
45,False,False,False,False,False,False,False,False,False
46,False,False,False,False,False,False,False,False,False
47,False,False,False,False,False,False,False,False,False
48,False,False,False,False,False,False,False,False,False
49,False,False,False,False,False,False,False,False,False
50,False,False,False,False,False,False,False,False,False

In [7]:
val_manquant= df.fillna
val_manquant

<bound method NDFrame.fillna of      id_client         nom   age type_contrat date_contrat    region   prime  \
0          100  Client_100  35.0         auto   2022-04-23   Savanes  324.63
1          298  Client_298  57.0         MOTO   2020-04-05  Plateaux  172.37
2           90   Client_90  65.0   habitation   2020-08-03  Plateaux  179.38
3           31   Client_31   NaN         auto   2021-02-05   Savanes  245.67
4          236  Client_236  69.0   habitation   2021-12-23  Maritime  130.21
..         ...         ...   ...          ...          ...       ...     ...
300        300  Client_300  35.0   habitation   2023-01-06   Savanes  246.54
301         23   Client_23  61.0        sante   2020-03-18  Plateaux  161.38
302         73   Client_73  57.0         auto   2022-10-17   Savanes  249.28
303         16   Client_16  57.0         auto   2022-03-08  Plateaux  343.54
304        169  Client_169   NaN        sante   2021-01-05  Maritime   60.17

     nb_sinistres  montant_sinistres
0               3             810.05
1               0               0.00
2               1             612.00
3               0               0.00
4               1             567.57
..            ...                ...
300             0               0.00
301             0               0.00
302             0               0.00
303             0               0.00
304             0               0.00

[305 rows x 9 columns]>

In [8]:
df.drop_duplicates

<bound method DataFrame.drop_duplicates of      id_client         nom   age type_contrat date_contrat    region   prime  \
0          100  Client_100  35.0         auto   2022-04-23   Savanes  324.63
1          298  Client_298  57.0         MOTO   2020-04-05  Plateaux  172.37
2           90   Client_90  65.0   habitation   2020-08-03  Plateaux  179.38
3           31   Client_31   NaN         auto   2021-02-05   Savanes  245.67
4          236  Client_236  69.0   habitation   2021-12-23  Maritime  130.21
..         ...         ...   ...          ...          ...       ...     ...
300        300  Client_300  35.0   habitation   2023-01-06   Savanes  246.54
301         23   Client_23  61.0        sante   2020-03-18  Plateaux  161.38
302         73   Client_73  57.0         auto   2022-10-17   Savanes  249.28
303         16   Client_16  57.0         auto   2022-03-08  Plateaux  343.54
304        169  Client_169   NaN        sante   2021-01-05  Maritime   60.17

     nb_sinistres  montant_sinistres
0               3             810.05
1               0               0.00
2               1             612.00
3               0               0.00
4               1             567.57
..            ...                ...
300             0               0.00
301             0               0.00
302             0               0.00
303             0               0.00
304             0               0.00

[305 rows x 9 columns]>

In [9]:
df.fillna(0)

,id_client,nom,age,type_contrat,date_contrat,region,prime,nb_sinistres,montant_sinistres
0,100,Client_100,35.0,auto,2022-04-23,Savanes,324.63,3,810.05
1,298,Client_298,57.0,MOTO,2020-04-05,Plateaux,172.37,0,0.00
2,90,Client_90,65.0,habitation,2020-08-03,Plateaux,179.38,1,612.00
3,31,Client_31,0.0,auto,2021-02-05,Savanes,245.67,0,0.00
4,236,Client_236,69.0,habitation,2021-12-23,Maritime,130.21,1,567.57
...,...,...,...,...,...,...,...,...,...
300,300,Client_300,35.0,habitation,2023-01-06,Savanes,246.54,0,0.00
301,23,Client_23,61.0,sante,2020-03-18,Plateaux,161.38,0,0.00
302,73,Client_73,57.0,auto,2022-10-17,Savanes,249.28,0,0.00
303,16,Client_16,57.0,auto,2022-03-08,Plateaux,343.54,0,0.00
304,169,Client_169,0.0,sante,2021-01-05,Maritime,60.17,0,0.00

In [10]:
df.isnull().sum()

id_client             0
nom                   0
age                  12
type_contrat          0
date_contrat          0
region                6
prime                 9
nb_sinistres          0
montant_sinistres     0
dtype: int64

In [11]:
df["age"] = df["age"].fillna(df["age"].median())   ##REMPLACER L'AGE VIDE PAR LA MEDIAN

In [12]:
df.isnull().sum()

id_client            0
nom                  0
age                  0
type_contrat         0
date_contrat         0
region               6
prime                9
nb_sinistres         0
montant_sinistres    0
dtype: int64

In [13]:
df

,id_client,nom,age,type_contrat,date_contrat,region,prime,nb_sinistres,montant_sinistres
0,100,Client_100,35.0,auto,2022-04-23,Savanes,324.63,3,810.05
1,298,Client_298,57.0,MOTO,2020-04-05,Plateaux,172.37,0,0.00
2,90,Client_90,65.0,habitation,2020-08-03,Plateaux,179.38,1,612.00
3,31,Client_31,46.0,auto,2021-02-05,Savanes,245.67,0,0.00
4,236,Client_236,69.0,habitation,2021-12-23,Maritime,130.21,1,567.57
...,...,...,...,...,...,...,...,...,...
300,300,Client_300,35.0,habitation,2023-01-06,Savanes,246.54,0,0.00
301,23,Client_23,61.0,sante,2020-03-18,Plateaux,161.38,0,0.00
302,73,Client_73,57.0,auto,2022-10-17,Savanes,249.28,0,0.00
303,16,Client_16,57.0,auto,2022-03-08,Plateaux,343.54,0,0.00
304,169,Client_169,46.0,sante,2021-01-05,Maritime,60.17,0,0.00

In [14]:
df.isnull().sum()

id_client            0
nom                  0
age                  0
type_contrat         0
date_contrat         0
region               6
prime                9
nb_sinistres         0
montant_sinistres    0
dtype: int64

In [15]:
df["prime"] = df["prime"].fillna(df["prime"].median())

In [16]:
df.isnull().sum()

id_client            0
nom                  0
age                  0
type_contrat         0
date_contrat         0
region               6
prime                0
nb_sinistres         0
montant_sinistres    0
dtype: int64

In [17]:
df["region"] = df["region"].fillna("Inconnue")

In [18]:
df.isnull().sum()

id_client            0
nom                  0
age                  0
type_contrat         0
date_contrat         0
region               0
prime                0
nb_sinistres         0
montant_sinistres    0
dtype: int64

In [19]:
df

,id_client,nom,age,type_contrat,date_contrat,region,prime,nb_sinistres,montant_sinistres
0,100,Client_100,35.0,auto,2022-04-23,Savanes,324.63,3,810.05
1,298,Client_298,57.0,MOTO,2020-04-05,Plateaux,172.37,0,0.00
2,90,Client_90,65.0,habitation,2020-08-03,Plateaux,179.38,1,612.00
3,31,Client_31,46.0,auto,2021-02-05,Savanes,245.67,0,0.00
4,236,Client_236,69.0,habitation,2021-12-23,Maritime,130.21,1,567.57
...,...,...,...,...,...,...,...,...,...
300,300,Client_300,35.0,habitation,2023-01-06,Savanes,246.54,0,0.00
301,23,Client_23,61.0,sante,2020-03-18,Plateaux,161.38,0,0.00
302,73,Client_73,57.0,auto,2022-10-17,Savanes,249.28,0,0.00
303,16,Client_16,57.0,auto,2022-03-08,Plateaux,343.54,0,0.00
304,169,Client_169,46.0,sante,2021-01-05,Maritime,60.17,0,0.00

In [20]:
df.loc[100:200]

,id_client,nom,age,type_contrat,date_contrat,region,prime,nb_sinistres,montant_sinistres
100,214,Client_214,58.0,auto,2022-12-08,Maritime,271.84,1,272.98
101,156,Client_156,22.0,auto,2023-12-01,Savanes,429.95,2,758.34
102,26,Client_26,19.0,habitation,2020-05-11,Plateaux,295.14,4,5424.83
103,119,Client_119,41.0,auto,2022-03-25,Maritime,381.70,0,0.00
104,104,Client_104,43.0,auto,2020-04-04,Savanes,331.67,1,901.42
...,...,...,...,...,...,...,...,...,...
196,28,Client_28,50.0,auto,2024-11-07,Maritime,188.64,0,0.00
197,101,Client_101,64.0,auto,2024-09-04,Centrale,292.16,1,616.08
198,178,Client_178,56.0,moto,2020-11-08,Savanes,115.86,0,0.00
199,188,Client_188,39.0,sante,2023-05-18,Plateaux,219.25,1,506.61
200,227,Client_227,32.0,auto,2021-07-14,Maritime,282.03,0,0.00

In [21]:
df.isnull().sum()

id_client            0
nom                  0
age                  0
type_contrat         0
date_contrat         0
region               0
prime                0
nb_sinistres         0
montant_sinistres    0
dtype: int64

In [22]:
df

,id_client,nom,age,type_contrat,date_contrat,region,prime,nb_sinistres,montant_sinistres
0,100,Client_100,35.0,auto,2022-04-23,Savanes,324.63,3,810.05
1,298,Client_298,57.0,MOTO,2020-04-05,Plateaux,172.37,0,0.00
2,90,Client_90,65.0,habitation,2020-08-03,Plateaux,179.38,1,612.00
3,31,Client_31,46.0,auto,2021-02-05,Savanes,245.67,0,0.00
4,236,Client_236,69.0,habitation,2021-12-23,Maritime,130.21,1,567.57
...,...,...,...,...,...,...,...,...,...
300,300,Client_300,35.0,habitation,2023-01-06,Savanes,246.54,0,0.00
301,23,Client_23,61.0,sante,2020-03-18,Plateaux,161.38,0,0.00
302,73,Client_73,57.0,auto,2022-10-17,Savanes,249.28,0,0.00
303,16,Client_16,57.0,auto,2022-03-08,Plateaux,343.54,0,0.00
304,169,Client_169,46.0,sante,2021-01-05,Maritime,60.17,0,0.00

In [25]:
df.isnull().sum()

id_client            0
nom                  0
age                  0
type_contrat         0
date_contrat         0
region               0
prime                0
nb_sinistres         0
montant_sinistres    0
dtype: int64

In [26]:
df["type_contrat"].unique()

array(['auto', 'moto', 'habitation', 'sante'], dtype=object)

In [27]:
df

,id_client,nom,age,type_contrat,date_contrat,region,prime,nb_sinistres,montant_sinistres
0,100,Client_100,35.0,auto,2022-04-23,Savanes,324.63,3,810.05
1,298,Client_298,57.0,moto,2020-04-05,Plateaux,172.37,0,0.00
2,90,Client_90,65.0,habitation,2020-08-03,Plateaux,179.38,1,612.00
3,31,Client_31,46.0,auto,2021-02-05,Savanes,245.67,0,0.00
4,236,Client_236,69.0,habitation,2021-12-23,Maritime,130.21,1,567.57
...,...,...,...,...,...,...,...,...,...
300,300,Client_300,35.0,habitation,2023-01-06,Savanes,246.54,0,0.00
301,23,Client_23,61.0,sante,2020-03-18,Plateaux,161.38,0,0.00
302,73,Client_73,57.0,auto,2022-10-17,Savanes,249.28,0,0.00
303,16,Client_16,57.0,auto,2022-03-08,Plateaux,343.54,0,0.00
304,169,Client_169,46.0,sante,2021-01-05,Maritime,60.17,0,0.00

4

In [29]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
300    False
301    False
302    False
303    False
304    False
Length: 305, dtype: bool

In [30]:
df.duplicated().sum()

np.int64(5)

In [48]:
a= {"salut" : 13, "kolo":23, "lol" :23}
b= {"pagui":43,"fer":4,"tolo":34,"kolokol":43,"hilo":34}
c= {"nom":54,"nkl":46,"gfds":32,"trf":54,"alpha":25,"kolo":43}
d= {"kolo":33,"dri":765,"uilo":55,"kadri":6,"foli": 76,"gjanta":45}

df = pd.DataFrame([a,b,c,d])
df

,salut,kolo,lol,pagui,fer,tolo,kolokol,hilo,nom,nkl,gfds,trf,alpha,dri,uilo,kadri,foli,gjanta
0,13.0,23.0,23.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,43.0,4.0,34.0,43.0,34.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,43.0,NaN,NaN,NaN,NaN,NaN,NaN,54.0,46.0,32.0,54.0,25.0,NaN,NaN,NaN,NaN,NaN
3,NaN,33.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,765.0,55.0,6.0,76.0,45.0

In [49]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 18 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   salut    1 non-null      float64
 1   kolo     3 non-null      float64
 2   lol      1 non-null      float64
 3   pagui    1 non-null      float64
 4   fer      1 non-null      float64
 5   tolo     1 non-null      float64
 6   kolokol  1 non-null      float64
 7   hilo     1 non-null      float64
 8   nom      1 non-null      float64
 9   nkl      1 non-null      float64
 10  gfds     1 non-null      float64
 11  trf      1 non-null      float64
 12  alpha    1 non-null      float64
 13  dri      1 non-null      float64
 14  uilo     1 non-null      float64
 15  kadri    1 non-null      float64
 16  foli     1 non-null      float64
 17  gjanta   1 non-null      float64
dtypes: float64(18)
memory usage: 708.0 bytes

In [50]:
df.isnull()

,salut,kolo,lol,pagui,fer,tolo,kolokol,hilo,nom,nkl,gfds,trf,alpha,dri,uilo,kadri,foli,gjanta
0,False,False,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
1,True,True,True,False,False,False,False,False,True,True,True,True,True,True,True,True,True,True
2,True,False,True,True,True,True,True,True,False,False,False,False,False,True,True,True,True,True
3,True,False,True,True,True,True,True,True,True,True,True,True,True,False,False,False,False,False

In [51]:
df.isnull().sum()

salut      3
kolo       1
lol        3
pagui      3
fer        3
tolo       3
kolokol    3
hilo       3
nom        3
nkl        3
gfds       3
trf        3
alpha      3
dri        3
uilo       3
kadri      3
foli       3
gjanta     3
dtype: int64

In [54]:
df["kolo"] = df["kolo"].fillna(df["kolo"].median())

In [1]:
df

NameError: name 'df' is not defined