<h1 align = "center" style = "color : blue"> Agrégez des données avec Pandas</h1>

## Les differentes methodes d'aggregations

In [1]:
import pandas as pd
import numpy as np

In [2]:
Data = {
    "NAS_2" :[12,18, 12, 11],
    "IAI" :[12,15,14,2],
    "EPL" :[18, 18, 16, 20],
    "LYKODA" : [12, 16, 13,12],
    "genre" : ["M", "F", "F", "M"]
}
df = pd.DataFrame(Data)
df

   NAS_2  IAI  EPL  LYKODA genre
0     12   12   18      12     M
1     18   15   18      16     F
2     12   14   16      13     F
3     11    2   20      12     M

In [3]:
df["Etudiant"] = ["Sakpani", "Pagui", "Soda", "hola"]

In [4]:
df

   NAS_2  IAI  EPL  LYKODA genre Etudiant
0     12   12   18      12     M  Sakpani
1     18   15   18      16     F    Pagui
2     12   14   16      13     F     Soda
3     11    2   20      12     M     hola

In [5]:
df.set_index("Etudiant", inplace = True)

In [6]:
df

          NAS_2  IAI  EPL  LYKODA genre
Etudiant
Sakpani      12   12   18      12     M
Pagui        18   15   18      16     F
Soda         12   14   16      13     F
hola         11    2   20      12     M

In [7]:
df.groupby("genre").agg({"NAS_2" : "mean"})      ##Methode avec groupby pareil a pivot_table

       NAS_2
genre
F       15.0
M       11.5

## Agrégez des lignes et des colonnes

Nous souhaitons donc avoir la même agrégation, mais avec cette fois-ci, en lignes nos agences, et en colonnes les différents types de prêts.

La méthode qui vous permettra de faire cela est la méthode .pivot_table . Celle-ci prend 4 arguments en paramètres :

    - index : variable(s) placée(s) en ligne ;

    - columns : variable(s) placée en colonne(s) ;

    - values : variable sur laquelle on va appliquer la fonction d’agrégation ;

    - aggfunc : fonction d’agrégation.

La méthode permettant la transformation inverse s’appelle melt . Je

####            .pivot_table

In [8]:
# df.pivot_table(index = "genre", columns = "EPL", values= "EPL", aggfunc = "mean")

In [9]:
df

          NAS_2  IAI  EPL  LYKODA genre
Etudiant
Sakpani      12   12   18      12     M
Pagui        18   15   18      16     F
Soda         12   14   16      13     F
hola         11    2   20      12     M

## En résumé

   <p> Pour agréger des données, il faut définir une ou plusieurs variables placées en index, pour former des groupes sur lesquels s’appliquera une fonction d’agrégation.

    Le résultat final d’une agrégation contiendra autant de lignes que de valeurs différentes dans la variable ou les variables choisies en index.

    Il existe deux méthodes en Python permettant de réaliser une agrégation :

        la méthodegroup_by ;

        la méthodepivot_table .

## Probleme :

### Contexte :

Vous l’avez probablement remarqué, certains clients ont contracté plusieurs prêts au sein de notre établissement. Cela fausse donc potentiellement les calculs réalisés jusque-là. Le responsable revient vers vous avec des demandes plus précises.
#### Consignes:

Voici l’e-mail qu’il vous a envoyé :

    Hello,

    J’aurais plusieurs demandes que je souhaiterais que tu traites dès que tu peux. On en aurait besoin pour le comité de direction prévu en fin de semaine. Pourrais-tu :

        créer un data frame de profil client pour avoir par client toutes les informations qui le concernent, résumées en une ligne ;

        calculer le nombre exact de personnes en état de situation bancaire risquée, à partir du taux d’endettement et de ces profils clients ;

        calculer le bénéfice total dégagé par chacune de nos agences, par type de prêt ;

        calculer les bénéfices moyens réalisés par chaque agence, pour chaque type de prêt, sous forme de tableau à double entrée ;

        me communiquer la ville qui semble la plus intéressante pour y développer les prêts immobiliers ?

    Merci d’avance.

In [10]:
prets = pd.read_csv("Donnes_Banques.csv")
prets.head()

,identifiant,ville,CP,revenu,remboursement,duree,type,taux_interet,taux_endete,cout_total,benefices
0,0,TOULOUSE,31100,3669.0,1130.05,240,immobilier,1.168,30.80,271212.0,131.99
1,1,PARIS,75009,5310.0,240.00,64,automobile,3.701,4.52,15360.0,23.69
2,1,PARIS,75009,5310.0,1247.85,300,immobilier,1.173,23.50,374355.0,182.97
3,2,MARSEILLE,13010,1873.0,552.54,240,immobilier,0.972,29.50,132609.6,53.71
4,3,MARSEILLE,13010,1684.0,586.03,180,immobilier,1.014,34.80,105485.4,44.57

<h2 align = "center"> (1) Créer un data frame de profil client pour avoir par clienttoutes les informations qui le concernent, résumées en une ligne ;</h2>

In [14]:
profil_clients = prets.groupby('identifiant')[['remboursement','taux_endete','cout_total','benefices']].sum()
profil_clients.reset_index(inplace=True)
profil_clients.head()

   identifiant  remboursement  taux_endete  cout_total  benefices
0            0        1130.05        30.80    271212.0     131.99
1            1        1487.85        28.02    389715.0     206.66
2            2         552.54        29.50    132609.6      53.71
3            3         586.03        34.80    105485.4      44.57
4            4         423.61        28.70    101666.4      51.21

### (2) calculer le nombre exact de personnes en état de situation bancaire risquée, à partir du taux d’endettement et de ces profils clients ;

In [ ]:
Taille = prets.loc[prets["taux_endete"]>35 , :].shape[0]
Taille

### (3) Calculer le bénéfice total dégagé par chacune de nos agences, par type de prêt ;

In [ ]:
prets.groupby("type")["benefices"].sum()

### (4) calculer les bénéfices moyens réalisés par chaque agence, pour chaque type de prêt, sous forme de tableau à double entrée ;

In [ ]:
prets.groupby(["ville", "type"])["benefices"].mean()

In [ ]:
Data = prets.pivot_table(index = "ville", columns ="type", values = "benefices", aggfunc = "mean")
Data

In [ ]:
Data.reset_index() #Retour au dataframe classique

### (5) me communiquer la ville qui semble la plus intéressante pour y développer les prêts immobiliers ?

In [ ]:
# Data = prets.groupby(["ville", "type"]).agg({"benefices" : "sum"})
# Data

In [ ]:
df = prets.pivot_table(index = "ville", columns ="type" , values = "benefices", aggfunc = "mean")
df

In [ ]:
df.sort_values("immobilier", ascending  = False)

### Nice ou paris ? est la ville qui semble la plus  intéressante pour y développer les prêts immobiliers