<h1 align = "center" style = "color :blue">Fusionnez des données avec Pandas</h1>

<div>
    <strong> Objectif :</strong><br>
    En Data Science, les données sont souvent réparties dans plusieurs DataFrames.
    <strong>merge()</strong> et <strong>concat()</strong> permettent de combiner ces données,
    mais ils ne fonctionnent pas de la même manière.
</div>

In [1]:
import numpy as np
import pandas as pd

<h2 style = "color  : blue">La fonction ou  méthode ** merge() ** </h2>

merge() permet de fusionner des donnees d'un DATAFRAME en utilisant une clé ou une colonne de corresponance
### *Syntaxe :*
<p>- A.merge(B) , merge est considerer ici comme une methode<br> - pd.merge(A,B) , fonction pandas</p>

In [2]:
clients = pd.DataFrame({"id_client": [1,2,3], "nom": ["Alice","Bob","Chloe"]})
clients #

   id_client    nom
0          1  Alice
1          2    Bob
2          3  Chloe

In [3]:
# # merge() : jointure sur unecolonne commune

# 
# pd.merge(clients, contrats, on=’id_client’, how=’outer’) # garde tout, meme sans
# correspondance

In [4]:
contrats = pd.DataFrame({"id_client":[1,2,4], "prime": [200,350,150]})
contrats

   id_client  prime
0          1    200
1          2    350
2          4    150

In [5]:
Dataset = pd.merge(clients, contrats)
Dataset

   id_client    nom  prime
0          1  Alice    200
1          2    Bob    350

In [6]:
# # En utlisant la fonction merge() , on remarque que le nouveau dataset affiche que deux ligne :
#    - En fait la fonction merge() fusionne les donnes en utilisant une correspondance du dataframe clients

In [7]:
#Autre methode

In [8]:
 pd.merge(clients, contrats, on="id_client", how="inner") # seulement les orrespondances

   id_client    nom  prime
0          1  Alice    200
1          2    Bob    350

In [9]:
pd.merge(clients, contrats, on="id_client", how="left") # garde tout "clients

   id_client    nom  prime
0          1  Alice  200.0
1          2    Bob  350.0
2          3  Chloe    NaN

In [10]:
pd.merge(clients, contrats, on="id_client", how="right") # garde tout les contrats

   id_client    nom  prime
0          1  Alice    200
1          2    Bob    350
2          4    NaN    150

In [11]:
pd.merge(clients, contrats, on="id_client", how="outer") # Garde tout meme sans correspondance

   id_client    nom  prime
0          1  Alice  200.0
1          2    Bob  350.0
2          3  Chloe    NaN
3          4    NaN  150.0

<h2 style = "color  : blue">La fonction ** concat() ** </h2>

In [12]:
df_2023 = pd.DataFrame({"nom": ["Alice"],"prime": [200]})
df_2023

     nom  prime
0  Alice    200

In [13]:
df_2024 = pd.DataFrame({"nom": ["Bob"], "prime": [350]})
df_2024

   nom  prime
0  Bob    350

In [14]:
pd.concat([df_2023, df_2024])  #On remarque qu;apres concatenation les deu lignes on meme index.Donc il faut coriger

     nom  prime
0  Alice    200
0    Bob    350

In [15]:
pd.concat([df_2023, df_2024], ignore_index = True) # Pour corriger on affecte True a ignore_index ==>Ingnore les indices

     nom  prime
0  Alice    200
1    Bob    350

In [16]:
## la concatenation peut se faire sous forme de ligne vertical ou horizontal , pour ce faire on utilise axis pour preciser

C= pd.concat([df_2023, df_2024], ignore_index = True, axis = 0) ## Concatenation  sur colone

L = pd.concat([df_2023, df_2024], ignore_index = True, axis = 1) ## Concatenation  sur une ligne

In [17]:
C #sur colonne

     nom  prime
0  Alice    200
1    Bob    350

In [18]:
L #Ligne

       0    1    2    3
0  Alice  200  Bob  350

## En résumé:

    Il existe deux façons de fusionner deux data frames : 

        si les data frames ont la même structure, on peut faire une concaténation via la fonction concat : mettre les 2 data frames bout à bout ;

        sinon, on peut faire une jointure via la fonction/méthode << merge >> .

    Une jointure permet de joindre les informations de 2 data frames à partir d’une clé, une variable commune aux 2 data frames.

    Il existe 4 types de jointures : 

       - la jointure interne qui conserve les clés se trouvant dans le premier ET le second data frame ;

       - la jointure à droite (ou à gauche) qui conserve uniquement les clés se trouvant dans le data frame à droite (ou à gauche),
           et complète les informations manquantes par des valeurs manquantes, ou NaN ;

       - la jointure externe qui conserve toutes les clés se trouvant dans le premier OU le second data frame.

Ressource : OpenClassroom

## Probleme :

### Contexte:

Nos informations sont partagées dans plusieurs fichiers. En effet, nous avons d’une part le fichier contenant l’ensemble 
des informations de prêts, que nous avons déjà utilisé à plusieurs reprises.  Nous avons d’autre part les informations 
sur nos clients qui se trouvent non pas dans un, mais dans deux autres fichiers.

Il serait bien plus pratique de pouvoir rassembler l’ensemble de ces fichiers en un seul.
### Consignes :

Votre tâche cette fois-ci va être de rassembler ces différents fichiers pour ouvrir les possibilités de traitement, 
d’analyse, etc. Pour cela, vous devez utiliser l’ensemble des jeux de données à votre disposition (les deux fichiers clients et le fichier de prêts),
et appliquer les différentes méthodes Pandas présentées dans cette partie, pour les fusionner.

Prêt ? C’est parti

### Solution :

### (1) importation des deux fichier

In [19]:
clients_1 = pd.read_csv('https://raw.githubusercontent.com/OpenClassrooms-Student-Center/fr-4452741-decouvrez-les-librairies-python-pour-la-data-science/main/data/clients.csv')
clients_1.head()

   identifiant                      email               nom genre
0            0  LaurentDagenais@rhyta.com  Laurent Dagenais     M
1            1      GuyMarois@fleckens.hu        Guy Marois     M
2            2  BeaufortLesage@einrot.com   Beaufort Lesage     M
3            3  RussellDurand@armyspy.com    Russell Durand     M
4            4       AlexisRiel@rhyta.com       Alexis Riel     M

In [20]:
clients_2 = pd.read_csv('https://raw.githubusercontent.com/OpenClassrooms-Student-Center/fr-4452741-decouvrez-les-librairies-python-pour-la-data-science/main/data/clients_suite.csv')
clients_2.head()

   identifiant                          email                 nom genre
0          150         RochMireault@gustr.com       Roch Mireault     M
1          151       NathalieCormier@cuvox.de    Nathalie Cormier     F
2          152      VallisMainville@gustr.com    Vallis Mainville     M
3          153  DanielleNeufville@teleworm.us  Danielle Neufville     F
4          154      AllyrianeRacine@gustr.com    Allyriane Racine     F

In [21]:
clients_1.shape[0] # Nombre total de clients dans le dataset client_1

150

In [22]:
clients_2.shape[0] #Nombre total de clients dans le dataset client_2

78

<h3 align = "center">(1) -La première mission va être de rassembler les deux dataframes clients_1 et clients_2 en un gros dataframe clients qui contiendra l'ensemble des informations de notre clientèle !</h3>

In [23]:
Dataset = pd.concat([clients_1 , clients_2], ignore_index = True) # Ici j'utilise concat pour concatener les deux dataframes car il ont une meme stricture

In [24]:
Dataset.head()

   identifiant                      email               nom genre
0            0  LaurentDagenais@rhyta.com  Laurent Dagenais     M
1            1      GuyMarois@fleckens.hu        Guy Marois     M
2            2  BeaufortLesage@einrot.com   Beaufort Lesage     M
3            3  RussellDurand@armyspy.com    Russell Durand     M
4            4       AlexisRiel@rhyta.com       Alexis Riel     M

In [25]:
Dataset.shape[0] # Nombre totales de clients apres concatenation

228

<h3 align = "center"> (2) -A présent, vous allez fusionner ce fichier clients avec les profils clients créés précédemment. Ces derniers se trouve dans le dataframe profil_clients qui a été généré en case 2. Vous pouvez nommer le dataframe final data :</h3>

In [26]:
profil_clients = pd.read_csv("profil_clients.csv") # importation du  dataset contenant le profil des clients
profil_clients.head()

   identifiant  remboursement  taux_endete  cout_total  benefices
0            0        1130.05        30.80    271212.0     131.99
1            1        1487.85        28.02    389715.0     206.66
2            2         552.54        29.50    132609.6      53.71
3            3         586.03        34.80    105485.4      44.57
4            4         423.61        28.70    101666.4      51.21

In [27]:
## Fusions des donnes dataset et leur profil

data = pd.merge(Dataset,profil_clients , on = "identifiant",how = "inner")
data.head()

,identifiant,email,nom,genre,remboursement,taux_endete,cout_total,benefices
0,0,LaurentDagenais@rhyta.com,Laurent Dagenais,M,1130.05,30.80,271212.0,131.99
1,1,GuyMarois@fleckens.hu,Guy Marois,M,1487.85,28.02,389715.0,206.66
2,2,BeaufortLesage@einrot.com,Beaufort Lesage,M,552.54,29.50,132609.6,53.71
3,3,RussellDurand@armyspy.com,Russell Durand,M,586.03,34.80,105485.4,44.57
4,4,AlexisRiel@rhyta.com,Alexis Riel,M,423.61,28.70,101666.4,51.21

<h3 align = "center"> (3) -Le service marketing de la banque nous a fourni un fichier dans lequel se trouve l'age de TOUS les clients de notre banque.</h3>

In [28]:
clients_age = pd.read_csv('https://raw.githubusercontent.com/OpenClassrooms-Student-Center/fr-4452741-decouvrez-les-librairies-python-pour-la-data-science/main/data/client_age.csv')
clients_age.head() #import du fichier contenant les ages de nos clients

   identifiant  age
0            0   54
1            1   23
2            2   30
3            3   42
4            4   47

<p>Ajoutez l'information de l'age au dataframe data. Cependant, il semble que certains des clients ayant contracté un prêt n'apparaissent pas dans ce fichier. On souhaite cependant garder toutes les informations de notre dataframe data : choisissez donc avec précaution les arguments !</p>

In [29]:
df = pd.merge(data, clients_age, on = "identifiant", how = "left") # Ici, l'enoncer nous 
#dit que il y'a certaain client qui n;ont pas communiquer leur ages  donc je vais garder tout les clients

In [30]:
df.head()

,identifiant,email,nom,genre,remboursement,taux_endete,cout_total,benefices,age
0,0,LaurentDagenais@rhyta.com,Laurent Dagenais,M,1130.05,30.80,271212.0,131.99,54.0
1,1,GuyMarois@fleckens.hu,Guy Marois,M,1487.85,28.02,389715.0,206.66,23.0
2,2,BeaufortLesage@einrot.com,Beaufort Lesage,M,552.54,29.50,132609.6,53.71,30.0
3,3,RussellDurand@armyspy.com,Russell Durand,M,586.03,34.80,105485.4,44.57,42.0
4,4,AlexisRiel@rhyta.com,Alexis Riel,M,423.61,28.70,101666.4,51.21,47.0

### 4- Netoyages des donnes du dataframe final

#### A-)  Detection des valeur manquants

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 228 entries, 0 to 227
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   identifiant    228 non-null    int64
 1   email          228 non-null    object
 2   nom            228 non-null    object
 3   genre          228 non-null    object
 4   remboursement  228 non-null    float64
 5   taux_endete    228 non-null    float64
 6   cout_total     228 non-null    float64
 7   benefices      228 non-null    float64
 8   age            223 non-null    float64
dtypes: float64(5), int64(1), object(3)
memory usage: 16.2+ KB

In [32]:
# D'apres c que la fonction infos nous renvois il y'a que 223 clients qui on leur ages, le reste n'on pas communiquer leur ages

In [33]:
df.isnull().sum() # Confirmation avec isnull().sum()

identifiant      0
email            0
nom              0
genre            0
remboursement    0
taux_endete      0
cout_total       0
benefices        0
age              5
dtype: int64

In [34]:
## Vrai on a que la colonne de l;age qui a des ages manqant

In [35]:
#Remplacons les ages manquant par : inconnnue
df["age"] = df["age"].fillna("inconnue")

In [36]:
df.isnull().sum()

identifiant      0
email            0
nom              0
genre            0
remboursement    0
taux_endete      0
cout_total       0
benefices        0
age              0
dtype: int64

In [37]:
# OK PROBLEME DE VALEUR MANQUANT RESOLUT

In [38]:
df.to_csv("DataClients.csv", index = False) #  sauvegarde du dataframe final