In [4]:
import pandas as pd
import numpy as np

## En résumé

<p>On peut sélectionner une ou plusieurs colonnes d’un data frame via la syntaxe  mon_dataframe[col], où col est soit le nom de la colonne à sélectionner (lorsqu’il n'y en a qu’une), soit une liste de noms de colonnes (lorsqu’il y en a plusieurs).</p>

    Une colonne d’un data frame est une Series Pandas.

    De nombreuses manipulations sont possibles avec/via des Series ; on peut notamment :

        modifier, ajouter ou supprimer une colonne ;

        modifier le nom d’une colonne via la méthode **.rename()** ;

        changer le type d’une colonne via la méthode **.astype()** ;

        trier un data frame via la méthode **.sort_values()**

## Manipulez un dataframe

<p>Nous allons travailler à présent sur notre fichier de prêts immobiliers.

Pour expliquer rapidement ce fichier, chaque ligne correspond à un prêt qui a été accordé à un de nos clients. 
Chaque client est identifié par… son identifiant ! Nous avons les informations suivantes :

    -la ville et le code postale de l’agence où le client a contracté le prêt
    -le revenu mensuel du client
    -les mensualités remboursées par le client
    -la durée du prêt contracté, en nombre de mois
    -le type de prêt
    -et enfin le taux d’intérêt

Votre rôle cette fois ci va être de modifier ce jeu de données pour calculer différentes variables nécessaires pour 
identifier les clients qui sont à la limite de leur capacité de remboursement et déterminer les bénéfices réalisées par la banque.</p>

In [2]:
prets = pd.read_csv("https://raw.githubusercontent.com/OpenClassrooms-Student-Center/fr-4452741-decouvrez-les-librairies-python-pour-la-data-science/main/data/prets.csv")
prets.head()

,identifiant,ville,CP,revenu,remboursement,duree,type,taux
0,0,TOULOUSE,31100,3669.0,1130.05,240,immobilier,1.168
1,1,PARIS,75009,5310.0,240.00,64,automobile,3.701
2,1,PARIS,75009,5310.0,1247.85,300,immobilier,1.173
3,2,MARSEILLE,13010,1873.0,552.54,240,immobilier,0.972
4,3,MARSEILLE,13010,1684.0,586.03,180,immobilier,1.014

<p>Dans un premier temps, créez une nouvelle variable calculant le taux d'endettement de chaque individu. Ce taux correspond au pourcentage du revenu remboursé chaque mois par un individu. Vous arrondirez le résultat à 2 chiffres après la virgule :</p>

In [25]:
prets["taux_endete"] = round((prets["remboursement"]/prets["revenu"])*100, 2)

In [26]:
prets.head()

,identifiant,ville,CP,revenu,remboursement,duree,type,taux_interet,taux_endete,cout_total,benefices
0,0,TOULOUSE,31100,3669.0,1130.05,240,immobilier,1.168,30.80,271212.0,13198.984000
1,1,PARIS,75009,5310.0,240.00,64,automobile,3.701,4.52,15360.0,2368.640000
2,1,PARIS,75009,5310.0,1247.85,300,immobilier,1.173,23.50,374355.0,18296.600625
3,2,MARSEILLE,13010,1873.0,552.54,240,immobilier,0.972,29.50,132609.6,5370.688800
4,3,MARSEILLE,13010,1684.0,586.03,180,immobilier,1.014,34.80,105485.4,4456.758150

<p>Pour éviter toute confusion, renommez la variable `taux` en `taux_interet` :</p>

In [11]:
prets.rename(columns = {"taux" : "taux_interet"}, inplace = True)

In [12]:
prets.head()

,identifiant,ville,CP,revenu,remboursement,duree,type,taux_interet,taux_endete
0,0,TOULOUSE,31100,3669.0,1130.05,240,immobilier,1.168,30.799945
1,1,PARIS,75009,5310.0,240.00,64,automobile,3.701,4.519774
2,1,PARIS,75009,5310.0,1247.85,300,immobilier,1.173,23.500000
3,2,MARSEILLE,13010,1873.0,552.54,240,immobilier,0.972,29.500267
4,3,MARSEILLE,13010,1684.0,586.03,180,immobilier,1.014,34.799881



<p> Nous allons à présent créer deux dernières variables :

    cout_total correspondant au cout total du pret à partir du remboursement et de la duree
    benefices correspondant aux bénéfices mensuels réalisés par la banque sur le prêt

Nous simplifierons ici le calcul des bénéfices par :

bénéfices = C∗T/24

avec :</p>

    C = cout total du prêt
    T = taux d'intérêt

In [14]:
prets["cout_total"] = prets["remboursement"]*prets["duree"]  # Calcul du cout totale que le client doit remboursser

In [15]:
prets.head()

,identifiant,ville,CP,revenu,remboursement,duree,type,taux_interet,taux_endete,cout_total
0,0,TOULOUSE,31100,3669.0,1130.05,240,immobilier,1.168,30.799945,271212.0
1,1,PARIS,75009,5310.0,240.00,64,automobile,3.701,4.519774,15360.0
2,1,PARIS,75009,5310.0,1247.85,300,immobilier,1.173,23.500000,374355.0
3,2,MARSEILLE,13010,1873.0,552.54,240,immobilier,0.972,29.500267,132609.6
4,3,MARSEILLE,13010,1684.0,586.03,180,immobilier,1.014,34.799881,105485.4

In [36]:
#Calcul du benefice en utilisan la formule  : C*T/24

prets["benefices"] = round((prets["cout_total"]*prets["taux_interet"]/100)/(24), 2) # La fonction round(operation , nombre) permet d'arrondir a un nombrre x

In [37]:
prets.head()

,identifiant,ville,CP,revenu,remboursement,duree,type,taux_interet,taux_endete,cout_total,benefices
0,0,TOULOUSE,31100,3669.0,1130.05,240,immobilier,1.168,30.80,271212.0,131.99
1,1,PARIS,75009,5310.0,240.00,64,automobile,3.701,4.52,15360.0,23.69
2,1,PARIS,75009,5310.0,1247.85,300,immobilier,1.173,23.50,374355.0,182.97
3,2,MARSEILLE,13010,1873.0,552.54,240,immobilier,0.972,29.50,132609.6,53.71
4,3,MARSEILLE,13010,1684.0,586.03,180,immobilier,1.014,34.80,105485.4,44.57

<p>A présent, nous souhaitons connaitre les 5 prêts sur lesquels nous produisons le plus de bénéfices.
Mettez en place une solution pour les afficher :</p>

In [38]:
Trie_Benefice = prets.sort_values("benefices", ascending = False) #Ordre decroissant 
benef_Max = Trie_Benefice.head()
benef_Max  #Les cinqs prets sur lesqeulless nous produisons plus de benefices

,identifiant,ville,CP,revenu,remboursement,duree,type,taux_interet,taux_endete,cout_total,benefices
8,7,NICE,6000,5486.0,2956.95,300,immobilier,1.184,53.9,887085.0,437.63
23,22,NICE,6300,5838.0,3018.25,240,immobilier,1.229,51.7,724380.0,370.94
186,173,PARIS,75006,6784.0,3744.77,180,immobilier,1.248,55.2,674058.6,350.51
242,226,PARIS,75002,5098.0,2910.96,240,immobilier,1.140,57.1,698630.4,331.85
181,168,PARIS,75003,6366.0,2807.41,240,immobilier,1.176,44.1,673778.4,330.15

#### Fin DE L'EXERCICE note : 4/10 : 
Car je ne je n'est pas utiliser la focntion round() pour l'arrondissement

In [39]:
prets.to_csv("Donnes_banques.csv", index =False) ## chargement des donnes dans un nouveau dataset